
ALTER TABLE `#__cck_core` ADD `author_id` INT NOT NULL DEFAULT '0' AFTER `storage_table`;
ALTER TABLE `#__cck_core` ADD `parent_id` INT NOT NULL DEFAULT '0' AFTER `author_id`;
ALTER TABLE `#__cck_core` ADD `date_time` DATETIME NOT NULL AFTER `parent_id`;

ALTER TABLE `#__cck_core_search_field` ADD `match_collection` VARCHAR( 50 ) NOT NULL AFTER `live_value`;
ALTER TABLE `#__cck_core_search_field` ADD `match_target` VARCHAR( 50 ) NOT NULL AFTER `match_mode`;

UPDATE `#__cck_core_fields` SET `size` = '28' WHERE `id` IN (27,37,38,39,51);
UPDATE `#__cck_core_fields` SET `title` = 'CCK Storage Location', `name` = 'cck_storage_location', `label` = 'Storage Location' WHERE `id` = 2;
UPDATE `#__cck_core_fields` SET `options` = 'Following Options=0||Alphabetical AZ=1||Alphabetical ZA=2' WHERE `id` = 15;
UPDATE `#__cck_core_fields` SET `required` = 'required' WHERE `id` = 20;
UPDATE `#__cck_core_fields` SET `selectlabel` = 'Select a Table' WHERE `id` = 29;
UPDATE `#__cck_core_fields` SET `cols` = '92' WHERE `id` = 32;
UPDATE `#__cck_core_fields` SET `options2` = '{"query":"","table":"#__extensions","name":"name","where":"type=\\"template\\"","value":"name","orderby":"name","language_detection":"joomla","language_codes":"EN,GB,US,FR","language_default":"EN"}' WHERE `id` = 35;
UPDATE `#__cck_core_fields` SET `options2` = '{"preparecontent":"","prepareform":"if ( $value == ''0'' ) {\\r\\n $c0 = ''checked=\\"checked\\"''; $c1 = ''''; $class = ''unpublish'';\\r\\n} else {\\r\\n $c0 = ''''; $c1 = ''checked=\\"checked\\"''; $class = ''publish'';\\r\\n}\\r\\n$form = ''<div>''\\r\\n      . ''<input type=\\"radio\\" id=\\"state0\\" name=\\"''.$name.''\\" value=\\"0\\" ''.$c0\\r\\n      . '' style=\\"display:none;\\" \\/>''\\r\\n      . ''<input type=\\"radio\\" id=\\"state1\\" name=\\"''.$name.''\\" value=\\"1\\" ''.$c1\\r\\n      . '' style=\\"display:none;\\" \\/>''\\r\\n      . ''<a href=\\"#\\" id=\\"state\\" class=\\"jgrid\\">''\\r\\n      . ''<span class=\\"state ''.$class.''\\">''\\r\\n      . ''<\\/span>''\\r\\n      . ''<\\/a>''\\r\\n      . ''<\\/div>'';"}', `script` = '$j("#state").click(function(){\r\n $j("#state input").removeAttr("checked");\r\n if ( $j("#state0").prop("checked") == true ) {\r\n  $j("#state span").removeClass("unpublish").addClass("publish");\r\n  $j("#state1").attr("checked", "checked");\r\n } else {\r\n  $j("#state span").removeClass("publish").addClass("unpublish");\r\n  $j("#state0").attr("checked", "checked");\r\n }\r\n});' WHERE `id` = 43;
UPDATE `#__cck_core_fields` SET `cols` = '92', `rows` = '1' WHERE `id` = 44;
UPDATE `#__cck_core_fields` SET `options2` = '{"query":"SELECT DISTINCT a.template AS text, a.template AS value FROM #__template_styles AS a LEFT JOIN #__cck_core_templates AS b ON b.name = a.template WHERE b.id AND b.mode=0 ORDER BY a.template","table":"#__content","name":"","where":"","value":"","orderby":"","language_detection":"joomla","language_codes":"EN,GB,US,FR","language_default":"EN"}' WHERE `id` = 56;
UPDATE `#__cck_core_fields` SET `options2` = '{"preparecontent":"","prepareform":"$checked1 = ( $config[''item'']->layer == ''fields'' ) ? ''checked=\\"checked\\"'' : '''';\\r\\n$checked2 = ( $config[''item'']->layer == ''options'' ) ? ''checked=\\"checked\\"'' : '''';\\r\\n$checked3 = ( $config[''item'']->layer == ''template'' ) ? ''checked=\\"checked\\"'' : '''';\\r\\n$selected1 = ( $config[''item'']->layer == ''fields'' ) ? ''selected'' : '''';\\r\\n$selected2 = ( $config[''item'']->layer == ''options'' ) ? ''selected'' : '''';\\r\\n$selected3 = ( $config[''item'']->layer == ''template'' ) ? ''selected'' : '''';\\r\\n\\r\\n$form = ''<fieldset id=\\"layer\\" class=\\"toggle\\">''\\r\\n      . ''<input type=\\"radio\\" id=\\"layer1\\" name=\\"layer\\" value=\\"fields\\" ''\\r\\n      . ''style=\\"display: none\\" ''.$checked1.'' \\/>''\\r\\n      . ''<input type=\\"radio\\" id=\\"layer2\\" name=\\"layer\\" value=\\"options\\" ''\\r\\n      . ''style=\\"display: none\\" ''.$checked2.'' \\/>''\\r\\n      . ''<input type=\\"radio\\" id=\\"layer3\\" name=\\"layer\\" value=\\"template\\" ''\\r\\n      . ''style=\\"display: none\\" ''.$checked3.'' \\/>''\\r\\n      . ''<label id=\\"layer1_label\\" for=\\"layer1\\" class=\\"toggle first ''.$selected1.''\\">''\\r\\n      . JText::_( ''COM_CCK_FIELDS'' ).''<\\/label>''\\r\\n      . ''<label id=\\"layer2_label\\" for=\\"layer2\\" class=\\"toggle ''.$selected2.''\\">''\\r\\n      . JText::_( ''COM_CCK_OPTIONS'' ).''<\\/label>''\\r\\n      . ''<label id=\\"layer3_label\\" for=\\"layer3\\" class=\\"toggle last ''.$selected3.''\\">''\\r\\n      . JText::_( ''COM_CCK_TEMPLATE'' ).''<\\/label>''\\r\\n      . ''<\\/fieldset>'';"}', `script` = '$j("#layer label").click(function(){\r\n $j("#layer label").removeClass(''selected''); $j(this).addClass(''selected'');\r\n var current = $j("#"+$j(this).attr(''for''));\r\n if (current.prop("checked") != true) {\r\n  $j("#layer input").removeAttr("checked"); current.attr("checked", "checked"); $j(".layers").slideUp(); if(current.val()=="options" && ($j("#client1").prop("checked") == true || $j("#client2").prop("checked") == true)){$j("#acl").slideDown();} else {$j("#acl").slideUp();} $j("#layer_"+current.val()).slideDown();\r\n }\r\n});' WHERE `id` = 57;
UPDATE `#__cck_core_fields` SET `options2` = '{"query":"","table":"#__cck_core_types","name":"title","where":"published=1","value":"name","orderby":"title","language_detection":"joomla","language_codes":"EN,GB,US,FR","language_default":"EN"}', `script` = 'var e="type"; var elem="#jform_trigger_"+e;\r\nvar file="file=administrator/components/com_cck/helpers/scripts/list_live.php";\r\n$j(elem).change(function() {\r\nif (!$j("#jform_title").val()) {\r\n$j("#jform_title").val($j(elem+" option[value=\\''"+$j(elem).val()+"\\'']").text());\r\n}\r\nvar type = "&e_name="+$j(elem).val();\r\nvar live = "&live="+$j("#jform_params_live").val();\r\nvar variat = "&variat="+$j("#jform_params_variation").val();\r\n $j.ajax({\r\n  cache: false, data: file+type+live+variat+"&elem="+e, type: "POST",\r\n  url: "index.php?option=com_cck&task=ajax&format=raw",\r\n  success: function(response){ $j("#list_live_show").html(response); } });\r\n});\r\nvar type = "&e_name="+$j(elem).val();\r\nvar live = "&live="+$j("#jform_params_live").val();\r\nvar variat = "&variat="+$j("#jform_params_variation").val();\r\n $j.ajax({\r\n  cache: false, data: file+type+live+variat+"&elem="+e, type: "POST",\r\n  url: "index.php?option=com_cck&task=ajax&format=raw",\r\n  success: function(response){ $j("#list_live_show").html(response); } });' WHERE `id` = 58;
UPDATE `#__cck_core_fields` SET `options2` = '{"query":"","table":"#__cck_core_searchs","name":"title","where":"published=1","value":"name","orderby":"title","language_detection":"joomla","language_codes":"EN,GB,US,FR","language_default":"EN"}', `script` = 'var e="search"; var elem="#jform_trigger_"+e;\r\nvar file="file=administrator/components/com_cck/helpers/scripts/list_live.php";\r\n$j(elem).change(function() {\r\nif (!$j("#jform_title").val()) {\r\n$j("#jform_title").val($j(elem+" option[value=\\''"+$j(elem).val()+"\\'']").text());\r\n}\r\nvar type = "&e_name="+$j(elem).val();\r\nvar live = "&live="+$j("#jform_params_live").val();\r\nvar variat = "&variat="+$j("#jform_params_variation").val();\r\n $j.ajax({\r\n  cache: false, data: file+type+live+variat+"&elem="+e, type: "POST",\r\n  url: "index.php?option=com_cck&task=ajax&format=raw",\r\n  success: function(response){ $j("#list_live_show").html(response); } });\r\n});\r\nvar type = "&e_name="+$j(elem).val();\r\nvar live = "&live="+$j("#jform_params_live").val();\r\nvar variat = "&variat="+$j("#jform_params_variation").val();\r\n $j.ajax({\r\n  cache: false, data: file+type+live+variat+"&elem="+e, type: "POST",\r\n  url: "index.php?option=com_cck&task=ajax&format=raw",\r\n  success: function(response){ $j("#list_live_show").html(response); } });' WHERE `id` = 59;
UPDATE `#__cck_core_fields` SET `options2` = '{"preparecontent":"","prepareform":"$checked1 = ( $config[''item'']->client == ''search'' ) ? ''checked=\\"checked\\"'' : '''';\\r\\n$checked2 = ( $config[''item'']->client == ''filter'' ) ? ''checked=\\"checked\\"'' : '''';\\r\\n$checked3 = ( $config[''item'']->client == ''order'' ) ? ''checked=\\"checked\\"'' : '''';\\r\\n$checked4 = ( $config[''item'']->client == ''list'' ) ? ''checked=\\"checked\\"'' : '''';\\r\\n$checked5 = ( $config[''item'']->client == ''item'' ) ? ''checked=\\"checked\\"'' : '''';\\r\\n$selected1 = ( $config[''item'']->client == ''search'' ) ? ''selected'' : '''';\\r\\n$selected2 = ( $config[''item'']->client == ''filter'' ) ? ''selected'' : '''';\\r\\n$selected3 = ( $config[''item'']->client == ''order'' ) ? ''selected'' : '''';\\r\\n$selected4 = ( $config[''item'']->client == ''list'' ) ? ''selected'' : '''';\\r\\n$selected5 = ( $config[''item'']->client == ''item'' ) ? ''selected'' : '''';\\r\\n\\r\\n$form = ''<fieldset id=\\"client\\" class=\\"toggle\\">''\\r\\n      . ''<input type=\\"radio\\" id=\\"client1\\" name=\\"client\\" value=\\"search\\" ''\\r\\n      . ''style=\\"display: none\\" ''.$checked1.'' \\/>''\\r\\n      \\/\\/. ''<input type=\\"radio\\" id=\\"client2\\" name=\\"client\\" value=\\"filter\\" ''\\r\\n      \\/\\/. ''style=\\"display: none\\" ''.$checked2.'' \\/>''\\r\\n      . ''<input type=\\"radio\\" id=\\"client3\\" name=\\"client\\" value=\\"order\\" ''\\r\\n      . ''style=\\"display: none\\" ''.$checked3.'' \\/>''\\r\\n      . ''<input type=\\"radio\\" id=\\"client4\\" name=\\"client\\" value=\\"list\\" ''\\r\\n      . ''style=\\"display: none\\" ''.$checked4.'' \\/>''\\r\\n      . ''<input type=\\"radio\\" id=\\"client5\\" name=\\"client\\" value=\\"item\\" ''\\r\\n      . ''style=\\"display: none\\" ''.$checked5.'' \\/>''\\r\\n      . ''<label id=\\"client1_label\\" for=\\"client1\\" class=\\"toggle first ''.$selected1.''\\">''\\r\\n      . JText::_( ''COM_CCK_SEARCH_FORM'' ).''<\\/label>''\\r\\n      \\/\\/. ''<label id=\\"client2_label\\" for=\\"client2\\" class=\\"toggle ''.$selected2.''\\">''\\r\\n      \\/\\/. JText::_( ''COM_CCK_FILTER_FORM'' ).''<\\/label>''\\r\\n      . ''<label id=\\"client3_label\\" for=\\"client3\\" class=\\"toggle ''.$selected3.''\\">''\\r\\n      . JText::_( ''COM_CCK_ORDER'' ).''<\\/label>''\\r\\n      . ''<label id=\\"client4_label\\" for=\\"client4\\" class=\\"toggle ''.$selected4.''\\">''\\r\\n      . JText::_( ''COM_CCK_LIST'' ).''<\\/label>''\\r\\n      . ''<label id=\\"client5_label\\" for=\\"client5\\" class=\\"toggle last ''.$selected5.''\\">''\\r\\n      . JText::_( ''COM_CCK_ITEM'' ).''<\\/label>''\\r\\n      . ''<\\/fieldset>'';"}' WHERE `id` = 68;
UPDATE `#__cck_core_fields` SET `defaultvalue` = 'type,field,search,template', `options` = 'Content Type=type||Field=field||Search Type=search||Template=template', `divider` = ',' WHERE `id` = 69;
UPDATE `#__cck_core_fields` SET `options2` = '{"preparecontent":"","prepareform":"if ( $value == ''0'' ) {\\r\\n $c0 = ''checked=\\"checked\\"''; $c1 = ''''; $class = ''unlinked'';\\r\\n} else {\\r\\n $c0 = ''''; $c1 = ''checked=\\"checked\\"''; $class = ''linked'';\\r\\n}\\r\\n$form = ''<div>''\\r\\n      . ''<input type=\\"radio\\" id=\\"''.$name.''0\\" name=\\"''.$name.''\\" value=\\"0\\" ''.$c0\\r\\n      . '' style=\\"display:none;\\" \\/>''\\r\\n      . ''<input type=\\"radio\\" id=\\"''.$name.''1\\" name=\\"''.$name.''\\" value=\\"1\\" ''.$c1\\r\\n      . '' style=\\"display:none;\\" \\/>''\\r\\n      . ''<a href=\\"#\\" id=\\"''.$name.''\\" class=\\"switch\\">''\\r\\n      . ''<span class=\\"''.$name.'' ''.$class.''\\">''\\r\\n      . ''<\\/span>''\\r\\n      . ''<\\/a>''\\r\\n      . ''<\\/div>'';"}', `script` = '' WHERE `id` = 106;
UPDATE `#__cck_core_fields` SET `options` = 'No=0||Below Field=1||Below FormValue=2||Below Label=3' WHERE `id` = 154;
UPDATE `#__cck_core_fields` SET `label` = 'Date Range' WHERE `id` = 166;
UPDATE `#__cck_core_fields` SET `options2` = '{"format":"Y-m-d","dates":"0","storage_format":"0","time":"12","time_pos":"right","theme":"steel","week_numbers":"0"}' WHERE `id` IN (350,351,352,357,360,362,363,386,388);
UPDATE `#__cck_core_fields` SET `options2` = '{"query":"","table":"#__extensions","name":"name","where":"type =\\"language\\" AND enabled = 1 AND client_id = 1 AND state = 0","value":"element","orderby":"name","language_detection":"joomla","language_codes":"EN,GB,US,FR","language_default":"EN"}' WHERE `id` = 367;
UPDATE `#__cck_core_fields` SET `options2` = '{"query":"","table":"#__extensions","name":"name","where":"type =\\"language\\" AND enabled = 1 AND client_id = 0 AND state = 0","value":"element","orderby":"name","language_detection":"joomla","language_codes":"EN,GB,US,FR","language_default":"EN"}' WHERE `id` = 368;

INSERT INTO `#__cck_core_fields` (`id`, `title`, `name`, `folder`, `type`, `description`, `published`, `label`, `selectlabel`, `display`, `required`, `validation`, `defaultvalue`, `options`, `options2`, `minlength`, `maxlength`, `size`, `cols`, `rows`, `ordering`, `sorting`, `divider`, `bool`, `location`, `extended`, `style`, `script`, `bool2`, `bool3`, `bool4`, `bool5`, `bool6`, `bool7`, `bool8`, `css`, `attributes`, `storage`, `storage_location`, `storage_table`, `storage_field`, `storage_field2`, `storage_params`, `storages`, `checked_out`, `checked_out_time`) VALUES
(174, 'Core Debug', 'core_debug', 3, 'select_simple', '', 0, 'Debug', ' ', 3, '', '', '0', 'OFF=0||Basic=1||Advanced=2', '', 0, 50, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'options[debug]', '', '', '', 0, '0000-00-00 00:00:00'),
(175, 'Core Cache', 'core_cache', 3, 'select_simple', '', 0, 'Cache', ' ', 3, '', '', '', 'OFF=0', '', 0, 50, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', 'joomla_article', '#__content', 'options[cache]', '', '', '', 0, '0000-00-00 00:00:00'),
(176, 'Core Message Style', 'core_message_style', 3, 'select_simple', '', 0, 'Message Style', ' ', 3, '', '', 'message', 'None=0||Joomla=optgroup||Error=error||Message=message||Notice=notice', '', 0, 50, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'options[message_style]', '', '', '', 0, '0000-00-00 00:00:00'),
(177, 'Core SEF', 'core_sef', 3, 'select_simple', '', 0, 'SEF Urls', ' ', 3, '', '', '1', 'OFF=0||Optimized=1||Short=2', '', 0, 50, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'options[sef]', '', '', '', 0, '0000-00-00 00:00:00'),
(178, 'Core Template Item', 'core_template_item', 3, 'select_dynamic', '', 0, 'Style', ' ', 3, '', '', '', '', '{"query":"","table":"#__template_styles","name":"title","where":"","value":"id"}', 0, 50, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'template_item', '', '', '', 0, '0000-00-00 00:00:00'),
(179, 'Core Action', 'core_action', 3, 'select_simple', '', 0, 'Action', ' ', 3, '', '', '0', 'None=0||Include File=file||Render Template=template', '', 0, 50, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'options[action]', '', '', '', 0, '0000-00-00 00:00:00'),
(180, 'Core Redirection Url (No Access)', 'core_redirection_url_no_access', 3, 'text', '', 0, 'Redirection Url', ' ', 3, '', '', 'index.php?option=com_users&view=login', '', '', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'options[redirection_url_no_access]', '', '', '', 0, '0000-00-00 00:00:00'),
(181, 'Core Action No Access', 'core_action_no_access', 3, 'select_simple', '', 0, 'Action', ' ', 3, '', '', 'redirection', 'None=0||Redirection=redirection', '', 0, 50, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'options[action_no_access]', '', '', '', 0, '0000-00-00 00:00:00'),
(182, 'Core Options Format Date', 'core_options_format_date', 3, 'select_simple', '', 0, 'Format', ' ', 3, '', '', '0', 'DATETIME=0||TIMESTAMP=1', '', 0, 50, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'json[options2][format_date]', '', '', '', 0, '0000-00-00 00:00:00'),
(183, 'Core Options Force Thumb Creation', 'core_options_force_thumb_creation', 3, 'select_simple', '', 0, 'Force Thumb Creation', ' ', 3, '', '', '', 'NONE_BP=0||NOT_EXIST=1||ALWAYS=2', '', 0, 50, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'json[options2][force_thumb_creation]', '', '', '', 0, '0000-00-00 00:00:00'),
(184, 'Core Options Orderby', 'core_options_orderby', 3, 'text', '', 0, 'Order By', ' ', 3, '', '', '', '', '', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'json[options2][orderby]', '', '', '', 0, '0000-00-00 00:00:00'),
(185, 'Core Options Language Codes', 'core_options_language_codes', 3, 'text', '', 0, 'Language Codes', ' ', 3, '', '', 'EN,GB,US,FR', '', '', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'json[options2][language_codes]', '', '', '', 0, '0000-00-00 00:00:00'),
(186, 'Core Options Language Default', 'core_options_language_default', 3, 'text', '', 0, 'Default Language', ' ', 3, '', '', 'EN', '', '', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'json[options2][language_default]', '', '', '', 0, '0000-00-00 00:00:00'),
(187, 'Core Options Language Detection', 'core_options_language_detection', 3, 'select_simple', '', 0, 'Language Detection', ' ', 3, '', '', 'joomla', 'Joomla=joomla||GeoIP=geoip', '', 0, 50, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'json[options2][language_detection]', '', '', '', 0, '0000-00-00 00:00:00'),
(3, 'CCK Storage Table', 'cck_storage_table', 3, 'text', '', 1, '', ' ', 3, '', '', '', '', '', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'standard', 'free', '#__cck_core', 'storage_table', '', '', '', 0, '0000-00-00 00:00:00'),
(4, 'CCK Author Id', 'cck_author_id', 3, 'text', '', 1, 'Author Id', ' ', 3, '', '', '', '', '', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'standard', 'free', '#__cck_core', 'author_id', '', '', '', 0, '0000-00-00 00:00:00'),
(5, 'CCK Parent Id', 'cck_parent_id', 3, 'text', '', 1, 'Parent Id', ' ', 3, '', '', '', '', '', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'standard', 'free', '#__cck_core', 'parent_id', '', '', '', 0, '0000-00-00 00:00:00'),
(6, 'CCK Date Time', 'cck_date_time', 3, 'text', '', 1, 'Date Time', ' ', 3, '', '', '', '', '', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'standard', 'free', '#__cck_core', 'date_time', '', '', '', 0, '0000-00-00 00:00:00'),
(188, 'Core Redirection', 'core_redirection', 3, 'select_simple', '', 0, 'Redirection', ' ', 3, '', '', 'current', 'Content=content||Current=current||Current Full=current_full||Form=form||Form Edition=form_edition||Url=url', '', 0, 50, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'options[redirection]', '', '', '', 0, '0000-00-00 00:00:00'),
(189, 'Core Redirection Url', 'core_redirection_url', 3, 'text', '', 0, 'Redirection Url', ' ', 3, 'required', '', '', '', '', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'options[redirection_url]', '', '', '', 0, '0000-00-00 00:00:00'),
(190, 'Core Dev Select', 'core_dev_select', 3, 'select_simple', '', 0, '', 'Select an Option', 3, '', '', '', '', '', 0, 50, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'select', '', '', '', 0, '0000-00-00 00:00:00'),
(191, 'Core Field Focus Border Color', 'core_field_focus_border_color', 3, 'colorpicker', '', 0, 'Focus Border Color', ' ', 3, '', '', '#888888', '', '', 0, 50, 16, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'field_focus_border_color', '', '', '', 0, '0000-00-00 00:00:00'),
(192, 'Core Storage Alter Table', 'core_storage_alter_table', 3, 'select_simple', '', 0, '', ' ', 3, '', '', '0', '_=0||Alter Original Table=1', '', 0, 50, 32, 0, 0, 0, 0, ',', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '#__assets', 'storage_alter_table', '', '', '', 0, '0000-00-00 00:00:00'),
(193, 'Core Options MultiValue Mode', 'core_options_multivalue_mode', 3, 'select_simple', '', 0, 'MultiValue Mode', ' ', 3, '', '', '', 'No Only Main Value=0||Yes=1', '', 0, 50, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'json[options2][multivalue_mode]', '', '', '', 0, '0000-00-00 00:00:00'),
(194, 'Core Validation Scroll', 'core_validation_scroll', 3, 'select_simple', '', 0, 'Scroll', ' ', 3, '', '', '1', 'Yes=1||No=0', '', 0, 50, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'options[validation_scroll]', '', '', '', 0, '0000-00-00 00:00:00'),
(195, 'Core Validation Position', 'core_validation_position', 3, 'select_simple', '', 0, 'Position', ' ', 3, '', '', 'topRight', 'Position topLeft=topLeft||Position topRight=topRight||Position centerRight=centerRight||Position bottomLeft=bottomLeft||Position bottomRight=bottomRight', '', 0, 50, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'options[validation_position]', '', '', '', 0, '0000-00-00 00:00:00'),
(196, 'Core Validation Style', 'core_validation_style', 3, 'select_simple', '', 0, 'Style', ' ', 3, '', '', 'balloon', 'Balloon=balloon||Text=text', '', 0, 50, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'options[validation_style]', '', '', '', 0, '0000-00-00 00:00:00'),
(197, 'Core Validation Color', 'core_validation_color', 3, 'colorpicker', '', 0, 'Color', ' ', 3, '', '', '', '', '', 0, 255, 16, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'options[validation_color]', '', '', '', 42, '2011-07-29 13:34:38'),
(198, 'Core Validation Background Color', 'core_validation_background_color', 3, 'colorpicker', '', 0, 'Background Color', ' ', 3, '', '', '', '', '', 0, 255, 16, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'options[validation_background_color]', '', '', '', 0, '0000-00-00 00:00:00'),
(199, 'Core Dev Textarea', 'core_dev_textarea', 3, 'textarea', '', 0, '', ' ', 3, '', '', '', '', '', 0, 255, 32, 25, 3, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'textarea', '', '', '', 0, '0000-00-00 00:00:00'),
(200, 'Core Options Html', 'core_options_html', 3, 'textarea', '', 0, 'Html', ' ', 3, '', '', '', '', '', 0, 0, 32, 92, 24, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'json[options2][html]', '', '', '', 0, '0000-00-00 00:00:00');

UPDATE `#__cck_core_fields` SET `options2` = '{"query":"","table":"#__template_styles","name":"title","where":"","value":"id","orderby":"","language_detection":"joomla","language_codes":"EN,GB,US,FR","language_default":"EN"}', `divider` = ',', `attributes` = 'style="max-width:190px;"' WHERE `id` IN (52,53,54,136,137,138,178);
UPDATE `#__cck_core_fields` SET `options` = 'On Upload=0||If Not Exist=1||Always=2' WHERE `id` = 183;

-- --------------------------------------------------------
ALTER TABLE `#__cck_core_search_field` ADD `typo_label` TINYINT( 4 ) NOT NULL DEFAULT '0' AFTER `typo`;
ALTER TABLE `#__cck_core_search_field` ADD `typo_options` VARCHAR( 1024 ) NOT NULL AFTER `typo_label`;

ALTER TABLE `#__cck_core_type_field` ADD `typo_label` TINYINT( 4 ) NOT NULL DEFAULT '0' AFTER `typo`;
ALTER TABLE `#__cck_core_type_field` ADD `typo_options` VARCHAR( 1024 ) NOT NULL AFTER `typo_label`;
-- --------------------------------------------------------

UPDATE `#__extensions` SET `enabled` = '1' WHERE `folder` = 'cck_field_typo' AND `element` = 'image';

UPDATE `#__extensions` SET `enabled` = '1' WHERE `folder` = 'cck_field' AND ( `element` = 'iframe' OR `element` = 'jform_helpsite' OR `element` = 'video_youtube' );

UPDATE `#__cck_core_searchs` SET `template_list` = 0;

INSERT INTO `#__cck_core_templates` (`title`, `name`, `folder`, `mode`, `description`, `published`, `checked_out`, `checked_out_time`) VALUES
('Blog', 'seb_blog', 3, 2, '', 1, 0, '0000-00-00 00:00:00'),
('Table', 'seb_table', 3, 2, '', 1, 0, '0000-00-00 00:00:00');