
INSERT INTO `#__cck_core_fields` (`id`, `title`, `name`, `folder`, `type`, `description`, `published`, `label`, `selectlabel`, `display`, `required`, `validation`, `defaultvalue`, `options`, `options2`, `minlength`, `maxlength`, `size`, `cols`, `rows`, `ordering`, `sorting`, `divider`, `bool`, `location`, `extended`, `style`, `script`, `bool2`, `bool3`, `bool4`, `bool5`, `bool6`, `bool7`, `bool8`, `css`, `attributes`, `storage`, `storage_location`, `storage_table`, `storage_field`, `storage_field2`, `storage_params`, `storages`, `checked_out`, `checked_out_time`) VALUES
(240, 'Core Class Clear', 'core_class_clear', 3, 'select_simple', '', 0, 'Clear', ' ', 3, '', '', '0', 'Yes=cck-clrfix||No=0', '', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'class_clear', '', '', '', 0, '0000-00-00 00:00:00'),
(241, 'Core Class Float', 'core_class_float', 3, 'select_simple', '', 0, 'Float', ' ', 3, '', '', '0', 'Left=cck-fl||None=0', '', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'class_float', '', '', '', 0, '0000-00-00 00:00:00'),
(242, 'Core Show Hide', 'core_show_hide', 3, 'select_simple', '', 0, 'Show', ' ', 3, '', '', '', 'Hide=0||Show=1', '', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'show', '', '', '', 0, '0000-00-00 00:00:00'),
(243, 'Core Label Total', 'core_label_total', 3, 'text', '', 0, 'Label', ' ', 3, '', '', 'Results', '', '', 0, 255, 8, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'label_total', '', '', '', 0, '0000-00-00 00:00:00'),
(244, 'Core Show Pagination', 'core_show_pagination', 3, 'select_simple', '', 0, 'Show Pagination', ' ', 3, '', '', '', 'Above=-1||Below=0||Both=1', '', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'show_pagination', '', '', '', 0, '0000-00-00 00:00:00'),
(245, 'Core Ordering', 'core_ordering', 3, 'select_simple', '', 0, 'Ordering', ' ', 3, '', '', '', 'Config Option Alphabetical=alpha||Config Option Most Popular=popular||Config Option Most Recent First=newest||Config Option Oldest First=oldest||Config Option Ordering=ordering', '', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'ordering', '', '', '', 0, '0000-00-00 00:00:00'),
(246, 'Core Ordering2', 'core_ordering2', 3, 'select_simple', '', 0, 'Ordering', ' ', 3, '', '', '', 'Custom sl=-1||Config Option Alphabetical=alpha||Config Option Most Popular=popular||Config Option Most Recent First=newest||Config Option Oldest First=oldest||Config Option Ordering=ordering', '', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'ordering', '', '', '', 0, '0000-00-00 00:00:00'),
(247, 'Core Order By', 'core_order_by', 3, 'text', '', 0, 'Order By', ' ', 3, '', '', '', '', '', 0, 255, 16, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'order_by', '', '', '', 0, '0000-00-00 00:00:00'),
(248, 'Core Item Display', 'core_item_display', 3, 'select_simple', '', 0, 'Rendering', ' ', 3, '', '', 'renderItem', 'Item Field Html=renderItemField_Html||Item Field Typo=renderItemField_Typo||Item Field Value=renderItemField_Value||Item=renderItem', '', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'display', '', '', '', 0, '0000-00-00 00:00:00'),
(249, 'Core Auto Custom', 'core_auto_custom', 3, 'select_simple', '', 0, 'Select', ' ', 3, '', '', '', 'Auto=0||Custom=1', '', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'auto_custom', '', '', '', 0, '0000-00-00 00:00:00'),
(250, 'Core Auto Deepest', 'core_auto_deepest', 3, 'select_simple', '', 0, 'Select', ' ', 3, '', '', '', 'Auto=0||Deepest=1', '', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'auto_deepest', '', '', '', 0, '0000-00-00 00:00:00'),
(251, 'Core Across Down', 'core_across_down', 3, 'select_simple', '', 0, 'Select', ' ', 3, '', '', '', 'Across=0||Down=1', '', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'across_down', '', '', '', 0, '0000-00-00 00:00:00'),
(252, 'Core Numeric 6', 'core_numeric_6', 3, 'select_numeric', '', 0, 'Select', ' ', 3, '', '', '', '', '{"math":"0","start":"1","first":"","step":"1","last":"","end":"6","force_digits":"0"}', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'numeric', '', '', '', 0, '0000-00-00 00:00:00');

UPDATE `#__cck_core_fields` SET `options2` = '{"preparecontent":"","prepareform":"require_once JPATH_ADMINISTRATOR.DS. ''components'' .DS. CCK_COM .DS. ''models'' .DS. ''fields'' .DS. ''core.php'';\\r\\n$value = ( $value ) ? $value : ''custom'';\\r\\n$options = array();\\r\\n$options[] = JHtml::_( ''select.option'', ''none'', ''- ''.JText::_( ''COM_CCK_NONE'' ).'' -'', ''value'', ''text'' );\\r\\n$my = JFactory::getUser();\\r\\n$iAmSuperAdmin = $my->authorise( ''core.admin'' );\\r\\nif ( ( JCck::getConfig_Param( ''storage_dev'', ''0'' ) == 1 && $iAmSuperAdmin === TRUE ) || ( $value == ''dev'' ) ) { $options[] = JHtml::_( ''select.option'', ''dev'', JText::_ ( ''COM_CCK_DEVELOPMENT'' ), ''value'', ''text'' );\\r\\n}\\r\\n$options = array_merge( $options, JFormFieldCore::getPluginTypes( ''storage'', ''cck_'', false, false, true ) );\\r\\n$form = JHtml::_( ''select.genericlist'', $options, $name, ''class=\\"inputbox select\\" size=\\"1\\" ''.$field->attributes, ''value'', ''text'', $value );","preparestore":""}', `script` = '$j("#storage").live(''change'', function() { var v = $j("#storage").val();\r\nif ( v == "dev" ) { $j("#storage_more, .storage_more").show();\r\n$j("#storage_location, #storage_table, #storage_alter").hide().attr("disabled", "disabled"); $j("#storage_field").removeAttr("disabled").show(); $j("#storage_field").val(""); } else { $j("#storage_more, .storage_more").hide(); if ( v == "none" ) { $j("#storage_location, #storage_table, #storage_alter").hide().attr("disabled", "disabled"); $j("#storage_field").hide().attr("disabled", "disabled"); } else { $j("#storage_location, #storage_field, #storage_alter").removeAttr("disabled").show(); if ( $j("#storage_location").val() == "free" ) { $j("#storage_table").attr("disabled", "").show(); } } } });\r\n$j("#storage_location").live(''change'', function() { var v = $j("#storage_location").val(); if ( v == "free" ) { $j("#storage_table").removeAttr("disabled").show(); } else { $j("#storage_table").hide().attr("disabled", "disabled");\r\n} });' WHERE `id` = 28;
UPDATE `#__cck_core_fields` SET `options2` = '{"preparecontent":"","prepareform":"require_once JPATH_ADMINISTRATOR.DS. ''components'' .DS. CCK_COM .DS. ''models'' .DS. ''fields'' .DS. ''core.php'';\\r\\n$options = JFormFieldCore::getFolderOptions( false, true, false, true, $config[''vName''] );\\r\\n$form = JHtml::_( ''select.genericlist'', $options, $name, ''class=\\"inputbox select\\" size=\\"1\\"'', ''value'', ''text'', $value, $id );","preparestore":""}' WHERE `id` = 41;
UPDATE `#__cck_core_fields` SET `label` = 'Status' WHERE `id` = 42;
UPDATE `#__cck_core_fields` SET `label` = 'Status' WHERE `id` = 43;
UPDATE `#__cck_core_fields` SET `options2` = '{"preparecontent":"","prepareform":"require_once JPATH_ADMINISTRATOR.DS. ''components'' .DS. CCK_COM .DS. ''models'' .DS. ''fields'' .DS. ''core.php'';\\r\\n$options = JFormFieldCore::getFolderOptions( true, true, true, true, $config[''vName''] );\\r\\n$form = JHtml::_( ''select.genericlist'', $options, $name, ''class=\\"inputbox select\\" size=\\"1\\" ''.$field->attributes, ''value'', ''text'', $value, $id );","preparestore":""}' WHERE `id` = 45;
UPDATE `#__cck_core_fields` SET `options2` = '{"preparecontent":"","prepareform":"require_once JPATH_ADMINISTRATOR.DS. ''components'' .DS. CCK_COM .DS. ''models'' .DS. ''fields'' .DS. ''core.php'';\\r\\n$options = JFormFieldCore::getLocationOptions();\\r\\n$form = JHtml::_( ''select.genericlist'', $options, $name, ''class=\\"inputbox select\\" size=\\"1\\" ''.$field->attributes, ''value'', ''text'', $value, $id );","preparestore":""}' WHERE `id` = 46;
UPDATE `#__cck_core_fields` SET `options2` = '{"preparecontent":"","prepareform":"require_once JPATH_ADMINISTRATOR.DS. ''components'' .DS. CCK_COM .DS. ''models'' .DS. ''fields'' .DS. ''core.php'';\\r\\n$options = JFormFieldCore::getPluginTypes( ''field'', ''cck_'', true, false, true );\\r\\n$form = JHtml::_( ''select.genericlist'', $options, $name, ''class=\\"inputbox select\\" size=\\"1\\" ''.$field->attributes, ''value'', ''text'', $value, $id );","preparestore":""}' WHERE `id` = 48;
UPDATE `#__cck_core_fields` SET `options2` = '{"preparecontent":"","prepareform":"require_once JPATH_ADMINISTRATOR.DS. ''components'' .DS. CCK_COM .DS. ''models'' .DS. ''fields'' .DS. ''core.php'';\\r\\n$options = JFormFieldCore::getPluginTypes( ''field'', ''cck_'', false, false, true );\\r\\n$form = JHtml::_( ''select.genericlist'', $options, $name, ''class=\\"inputbox select\\" size=\\"1\\" ''.$field->attributes, ''value'', ''text'', $value, $id );","preparestore":""}' WHERE `id` = 49;
UPDATE `#__cck_core_fields` SET `options2` = '{"preparecontent":"","prepareform":"require_once JPATH_ADMINISTRATOR.DS. ''components'' .DS. CCK_COM .DS. ''models'' .DS. ''fields'' .DS. ''core.php'';\\r\\nif ( @$config[''item'']->id == 1 || @$config[''item'']->id == 2 ) {\\r\\n $options = array();\\r\\n $options[] = JHtml::_( ''select.option'',  0, ''#'', ''value'', ''text'' );\\r\\n $disabled = '' disabled=\\"disabled\\" '';\\r\\n} else {\\r\\n $options = JFormFieldCore::getFolderOptions( false, false, true );\\r\\n $disabled = '''';\\r\\n}\\r\\n$form = JHtml::_( ''select.genericlist'', $options, $name, ''class=\\"inputbox select\\" size=\\"1\\" ''.$disabled.$field->attributes, ''value'', ''text'', $value, $id );","preparestore":""}' WHERE `id` = 50;
UPDATE `#__cck_core_fields` SET `label` = 'Storage Location' WHERE `id` = 66;
UPDATE `#__cck_core_fields` SET `defaultvalue` = 'left' WHERE `id` = 92;
UPDATE `#__cck_core_fields` SET `options2` = '{"preparecontent":"","prepareform":"require_once JPATH_ADMINISTRATOR.DS. ''components'' .DS. ''com_cck'' .DS. ''helpers'' .DS. ''helper_selectable.php'';\\r\\n$options = Helper_Selectable::getPositionVariations( @$config[''item'']->template, false );\\r\\n$attr = ''class=\\"inputbox\\" size=\\"1\\"'';\\r\\n$form = JHtml::_( ''select.genericlist'', $options, $name, $attr, ''value'', ''text'', $value, $id );","preparestore":""}' WHERE `id` = 107;
UPDATE `#__cck_core_fields` SET `options2` = '{"math":"0","start":"0","first":"","step":"1","last":"","end":"10"}' WHERE `id` = 155;
UPDATE `#__cck_core_fields` SET `options2` = '{"preparecontent":"","prepareform":"require_once JPATH_ADMINISTRATOR.DS. ''components'' .DS. CCK_COM .DS. ''models'' .DS. ''fields'' .DS. ''core.php'';\\r\\n$type = ( $field->location ) ? $field->location : ''field'';\\r\\n$opts = array();\\r\\nif ( trim( $field->selectlabel ) ) {\\r\\n  $selectlabel = ''COM_CCK_'' . str_replace( '' '', ''_'', trim( $field->selectlabel ) );\\r\\n  $opts[] = JHtml::_( ''select.option'','''',''- ''.JText::_( $selectlabel ).'' -'',''value'',''text'' );\\r\\n}\\r\\n$opts = array_merge( $opts, JFormFieldCore::getPluginTypes( $type, ''cck_'', false, false, true ) );\\r\\n$css  = ( $field->required == ''required'' ) ? '' validate[required]'' : '''';\\r\\n$form = JHtml::_( ''select.genericlist'', $opts, $name, ''class=\\"inputbox select''.$css.''\\" size=\\"1\\" ''.$field->attributes, ''value'', ''text'', $value, $id );","preparestore":""}' WHERE `id` = 232;

-- --------------------------------------------------------

UPDATE `#__extensions` SET `enabled` = '1' WHERE `folder` = 'cck_field_typo' AND ( `element` = 'clear' );