
ALTER TABLE `#__cck_core_types` ADD `location` VARCHAR( 50 ) NOT NULL AFTER `options_intro`;
ALTER TABLE `#__cck_core_type_field` CHANGE `conditional` `conditional` VARCHAR( 1024 ) NOT NULL;
ALTER TABLE `#__cck_core_type_field` CHANGE `conditional_options` `conditional_options` VARCHAR( 2048 ) NOT NULL;
ALTER TABLE `#__cck_core_search_field` CHANGE `conditional` `conditional` VARCHAR( 1024 ) NOT NULL;
ALTER TABLE `#__cck_core_search_field` CHANGE `conditional_options` `conditional_options` VARCHAR( 2048 ) NOT NULL;

INSERT IGNORE INTO `#__cck_core_fields` (`id`, `title`, `name`, `folder`, `type`, `description`, `published`, `label`, `selectlabel`, `display`, `required`, `validation`, `defaultvalue`, `options`, `options2`, `minlength`, `maxlength`, `size`, `cols`, `rows`, `ordering`, `sorting`, `divider`, `bool`, `location`, `extended`, `style`, `script`, `bool2`, `bool3`, `bool4`, `bool5`, `bool6`, `bool7`, `bool8`, `css`, `attributes`, `storage`, `storage_location`, `storage_table`, `storage_field`, `storage_field2`, `storage_params`, `storages`, `checked_out`, `checked_out_time`) VALUES
(275, 'Core Storage Location2', 'core_storage_location2', 3, '42', '', 0, 'Content Object', ' ', 3, '', '', 'joomla_article', '', '{"preparecontent":"","prepareform":"require_once JPATH_ADMINISTRATOR.DS. ''components'' .DS. CCK_COM .DS. ''models'' .DS. ''fields'' .DS. ''core.php'';\\r\\n\\r\\n$options = array();\\r\\nif ( trim( $field->selectlabel ) ) {\\r\\n  $options = array( JHtml::_( ''select.option'',  '''', ''- ''.$field->selectlabel.'' -'' ),\\r\\n                    JHtml::_( ''select.option'', ''none'', JText::_( ''COM_CCK_NONE'' ) ) );\\r\\n} else {\\r\\n  $value = ( $value ) ? $value : ''joomla_article'';\\r\\n  $options = array( JHtml::_( ''select.option'', ''none'', JText::_( ''COM_CCK_NONE'' ) ) );\\r\\n}\\r\\n$options = array_merge( $options, JFormFieldCore::getPluginTypes( ''storage_location'', ''cck_'', false, false, true ) );\\r\\n$form = JHtml::_( ''select.genericlist'', $options, $name, ''class=\\"inputbox select\\" size=\\"1\\" ''.$field->attributes, ''value'', ''text'', $value, $id );","preparestore":""}', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'storage_location', '', '', '', 0, '0000-00-00 00:00:00'),
(276, 'Core Location', 'core_location', 3, 'select_simple', '', 0, 'Create', ' ', 3, '', '', '', 'No=none||Yes=||location=optgroup||Administrator=admin||Site=site', '', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'location', '', '', '', 0, '0000-00-00 00:00:00'),
(277, 'Core Cache2', 'core_cache2', 3, 'select_simple', '', 0, 'Cache', ' ', 3, '', '', '0', 'OFF=0', '', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'options[cache2]', '', '', '', 0, '0000-00-00 00:00:00'),
(439, 'Category Left', 'cat_lft', 23, 'text', '', 1, 'Left', ' ', 3, '', '', '', '', '', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'standard', 'joomla_category', '#__categories', 'lft', '', '', '', 0, '0000-00-00 00:00:00'),
(440, 'Category Right', 'cat_rgt', 23, 'text', '', 1, 'Right', ' ', 3, '', '', '', '', '', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'standard', 'joomla_category', '#__categories', 'rgt', '', '', '', 0, '0000-00-00 00:00:00'),
(441, 'Category Path', 'cat_path', 23, 'text', '', 1, 'Path', ' ', 3, '', '', '', '', '', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'standard', 'joomla_category', '#__categories', 'path', '', '', '', 0, '0000-00-00 00:00:00'),
(442, 'Category Level', 'cat_level', 23, 'text', '', 1, 'Level', ' ', 3, '', '', '', '', '', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'standard', 'joomla_category', '#__categories', 'level', '', '', '', 0, '0000-00-00 00:00:00'),
(278, 'Core Stages', 'core_stages', 3, 'select_numeric', '', 0, 'Stages', ' ', 3, '', '', '1', '', '{"math":"0","start":"1","first":"","step":"1","last":"","end":"6","force_digits":"0"}', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'options[stages]', '', '', '', 0, '0000-00-00 00:00:00'),
(444, 'Button Next (2)', 'button_next_2', 3, 'button_submit', '', 1, 'Next', ' ', 3, '', '', '', '', '{"alt_link_text":"","alt_link":"","alt_link_options":""}', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'none', '', '', 'button_next_2', '', '', '', 0, '0000-00-00 00:00:00'),
(443, 'Button Next', 'button_next', 3, 'button_submit', '', 1, 'Next', ' ', 3, '', '', '', '', '{"alt_link_text":"","alt_link":"","alt_link_options":""}', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'none', '', '', 'button_next', '', '', '', 0, '0000-00-00 00:00:00'),
(445, 'Button Next (3)', 'button_next_3', 3, 'button_submit', '', 1, 'Next', ' ', 3, '', '', '', '', '{"alt_link_text":"","alt_link":"","alt_link_options":""}', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'none', '', '', 'button_next_3', '', '', '', 0, '0000-00-00 00:00:00');

UPDATE `#__cck_core_fields` SET `options` = "All SL=-1||On=1||Off=0" WHERE `id` = 42;
UPDATE `#__cck_core_fields` SET `options` = "All Types SL=||Content Form=0||List=2" WHERE `id` = 47;
UPDATE `#__cck_core_fields` SET `options2` = '{"query":"","table":"#__cck_core_types","name":"title","where":"published = 1 AND location != \\"admin\\" AND location != \\"none\\" AND storage_location != \\"none\\"","value":"name","orderby":"title","orderby_direction":"ASC","limit":"","language_detection":"joomla","language_codes":"EN,GB,US,FR","language_default":"EN"}' WHERE `id` = 58;
UPDATE `#__cck_core_fields` SET `options` = "OFF=0||ON=1" WHERE `id` = 174;
UPDATE `#__cck_core_fields` SET `defaultvalue` = '0', `options` = "OFF=0||ON=optgroup||Global=1||Self=2" WHERE `id` = 175;
UPDATE `#__cck_core_fields` SET `options2` = '{"preparecontent":"","prepareform":"require_once JPATH_ADMINISTRATOR.DS. ''components'' .DS. CCK_COM .DS. ''models'' .DS. ''fields'' .DS. ''core.php'';\\r\\n$type = ( $field->location ) ? $field->location : ''field'';\\r\\n$opts = array();\\r\\nif ( trim( $field->selectlabel ) ) {\\r\\n  $opts[] = JHtml::_( ''select.option'','''',''- ''.$field->selectlabel.'' -'',''value'',''text'' );\\r\\n}\\r\\n$opts = array_merge( $opts, JFormFieldCore::getPluginTypes( $type, ''cck_'', false, false, true ) );\\r\\n$css  = ( $field->required == ''required'' ) ? '' validate[required]'' : '''';\\r\\n$form = JHtml::_( ''select.genericlist'', $opts, $name, ''class=\\"inputbox select''.$css.''\\" size=\\"1\\" ''.$field->attributes, ''value'', ''text'', $value, $id );","preparestore":""}' WHERE `id` = 232;

UPDATE `#__cck_core_fields` SET `label` = 'Storage' WHERE `id` = 33;
UPDATE `#__cck_core_fields` SET `label` = 'Depth' WHERE `id` = 70;
UPDATE `#__cck_core_fields` SET `label` = 'Alter' WHERE `id` = 76;
UPDATE `#__cck_core_fields` SET `label` = 'Alter' WHERE `id` = 192;
UPDATE `#__cck_core_fields` SET `label` = 'clear' WHERE `id` IN (71,72,73,74,171,190,199,228,233,253,254);
UPDATE `#__cck_core_fields` SET `options` = 'Target Blank=_blank||Target Self=_self||Target Parent=_parent||Target Top=_top' WHERE `id` = 161;

UPDATE `#__cck_core_fields` SET `maxlength` = '1', `size` = '3' WHERE `id` = 267;
UPDATE `#__cck_core_fields` SET `defaultvalue` = '0', `options` = '_=0||Event Change=change||Event Keyup=keyup||None=none' WHERE `id` = 268;
UPDATE `#__cck_core_fields` SET `options` = 'Global=global||Self=0' WHERE `id` = 270;