
ALTER TABLE `#__cck_core_searchs` ADD `access` INT( 10 ) UNSIGNED NOT NULL DEFAULT '1' AFTER `description`;
ALTER TABLE `#__cck_core_sites` ADD `options` VARCHAR( 2048 ) NOT NULL AFTER `configuration`;
ALTER TABLE `#__cck_core_versions` ADD `user_id` INT NOT NULL DEFAULT '0' AFTER `date_time`;
ALTER TABLE `#__cck_core_fields` CHANGE `bool8` `bool8` TINYINT( 4 ) NOT NULL DEFAULT '1';

INSERT IGNORE INTO `#__cck_core_fields` (`id`, `title`, `name`, `folder`, `type`, `description`, `published`, `label`, `selectlabel`, `display`, `required`, `validation`, `defaultvalue`, `options`, `options2`, `minlength`, `maxlength`, `size`, `cols`, `rows`, `ordering`, `sorting`, `divider`, `bool`, `location`, `extended`, `style`, `script`, `bool2`, `bool3`, `bool4`, `bool5`, `bool6`, `bool7`, `bool8`, `css`, `attributes`, `storage`, `storage_location`, `storage_table`, `storage_field`, `storage_field2`, `storage_params`, `storages`, `checked_out`, `checked_out_time`) VALUES
(290, 'Core Joomla! Article Catid', 'core_joomla_article_catid', 3, 'jform_category', '', 0, 'Category', 'Use Global', 3, '', '', '', '', '{"extension":"com_content"}', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 1, 'max-width-200', '', 'dev', '', '', 'values[catid]', '', '', '', 0, '0000-00-00 00:00:00'),
(291, 'Core Joomla! Article Created By', 'core_joomla_article_created_by', 3, 'select_dynamic', '', 0, 'Author', 'Use Global', 3, '', '', '', '', '{"query":"SELECT id AS value, name AS text FROM #__users AS a LEFT JOIN #__user_usergroup_map AS b ON b.user_id = a.id WHERE b.group_id = 8 ORDER BY text","table":"#__content","name":"","where":"","value":"","orderby":"","orderby_direction":"ASC","limit":"","language_detection":"joomla","language_codes":"EN,GB,US,FR","language_default":"EN"}', 0, 255, 32, 0, 0, 0, 0, ',', 0, '', '', '', '', 1, 0, 0, 0, 0, 0, 1, '', '', 'dev', '', '', 'values[created_by]', '', '', '', 0, '0000-00-00 00:00:00'),
(292, 'Core Joomla! Article State', 'core_joomla_article_state', 3, 'select_simple', '', 0, 'Status', 'Use Global', 3, '', '', '', 'Published=1||Unpublished=0||Archived=2||Trashed=-2', '{"options":[]}', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 1, '', '', 'dev', '', '', 'values[state]', '', '', '', 0, '0000-00-00 00:00:00'),
(450, 'Core Joomla! Category Created By', 'core_joomla_category_created_by', 3, 'select_dynamic', '', 0, 'Author', 'Use Global', 3, '', '', '', '', '{"query":"SELECT id AS value, name AS text FROM #__users AS a LEFT JOIN #__user_usergroup_map AS b ON b.user_id = a.id WHERE b.group_id = 8 ORDER BY text","table":"#__content","name":"","where":"","value":"","orderby":"","orderby_direction":"ASC","limit":"","language_detection":"joomla","language_codes":"EN,GB,US,FR","language_default":"EN"}', 0, 255, 32, 0, 0, 0, 0, ',', 0, '', '', '', '', 1, 0, 0, 0, 0, 0, 1, '', '', 'dev', '', '', 'values[created_user_id]', '', '', '', 0, '0000-00-00 00:00:00'),
(451, 'Core Joomla! Category Parent Id', 'core_joomla_category_parent_id', 3, 'jform_category', '', 0, 'Parent', 'Use Global', 3, '', '', '', '', '{"extension":""}', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 1, 'max-width-200', '', 'dev', '', '', 'values[parent_id]', '', '', '', 0, '0000-00-00 00:00:00'),
(452, 'Core Joomla! Category State', 'core_joomla_category_state', 3, 'select_simple', '', 0, 'Status', 'Use Global', 3, '', '', '', 'Published=1||Unpublished=0||Archived=2||Trashed=-2', '{"options":[]}', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 1, '', '', 'dev', '', '', 'values[published]', '', '', '', 0, '0000-00-00 00:00:00'),
(453, 'Core Joomla! User Groups', 'core_joomla_user_groups', 3, 'select_dynamic', '', 0, 'User Groups', ' ', 3, '', '', '', '', '{"query":"","table":"#__usergroups","name":"title","where":"","value":"id","orderby":"lft","orderby_direction":"ASC","limit":"","language_detection":"joomla","language_codes":"EN,GB,US,FR","language_default":"EN"}', 0, 255, 32, 0, 9, 0, 0, ',', 0, '', '', '', '', 0, 1, 0, 0, 0, 0, 1, '', '', 'dev', '', '', 'values[groups]', '', '', '', 0, '0000-00-00 00:00:00'),
(454, 'Core List Display', 'core_list_display', 3, 'select_simple', '', 0, 'Display', ' ', 3, '', '', '0', 'Standard List View=0||Advanced Item View=1', '{"options":[]}', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 1, '', 'onchange="JCck.Dev.doSubmit();"', 'dev', '', '', 'display', '', '', '', 0, '0000-00-00 00:00:00'),
(456, 'Core Access', 'core_access', 3, 'jform_accesslevel', '', 0, 'Access', ' ', 3, '', '', '1', '', '', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 1, '', '', 'dev', '', '', 'access', '', '', '', 0, '0000-00-00 00:00:00'),
(455, 'Core Client Filter', 'core_client_filter', 3, '42', '', 0, 'Location', ' ', 3, '', '', '', '', '{"preparecontent":"","prepareform":"$options = Helper_Admin::getClientOptions( true, false, true );\\r\\n$class = $field->css ? '' ''.$field->css : '''';\\r\\n$form = JHtml::_( ''select.genericlist'', $options, $name, ''class=\\"inputbox select''.$class.''\\" size=\\"1\\" ''.$field->attributes, ''value'', ''text'', $value, $id );","preparestore":""}', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 1, '', 'onchange="this.form.submit()"', 'dev', '', '', 'filter_client', '', '', '', 0, '0000-00-00 00:00:00');

UPDATE `#__cck_core_fields` SET `script` = '' WHERE `id` = 28;
UPDATE `#__cck_core_fields` SET `defaultvalue` = '' WHERE `id` = 34;
UPDATE `#__cck_core_fields` SET `options` = 'All Status SL=-1||On=1||Off=0' WHERE `id` = 42;
UPDATE `#__cck_core_fields` SET `options2` = '{"preparecontent":"","prepareform":"$class = $field->css ? '' ''.$field->css : '''';\\r\\n$options = Helper_Admin::getFolderOptions( true, true, true, true, $config[''vName''] );\\r\\n$form = JHtml::_( ''select.genericlist'', $options, $name, ''class=\\"inputbox select''.$class.''\\" size=\\"1\\" ''.$field->attributes, ''value'', ''text'', $value, $id );","preparestore":""}' WHERE `id` = 45;
UPDATE `#__cck_core_fields` SET `options2` = '{"preparecontent":"","prepareform":"$class = $field->css ? '' ''.$field->css : '''';\\r\\n$options = Helper_Admin::getPluginOptions( ''field'', ''cck_'', true, false, true );\\r\\n$form = JHtml::_( ''select.genericlist'', $options, $name, ''class=\\"inputbox select''.$class.''\\" size=\\"1\\" ''.$field->attributes, ''value'', ''text'', $value, $id );","preparestore":""}' WHERE `id` = 48;
UPDATE `#__cck_core_fields` SET `options2` = '{"preparecontent":"","prepareform":"$value = ( $value ) ? $value : ''joomla_article'';\\r\\n$options = array();\\r\\n$options = array_merge( $options, Helper_Admin::getPluginOptions( ''storage_location'', ''cck_'', false, false, true ) );\\r\\n\\r\\n$attr = ''data-cck'';\\r\\n$base = JPATH_SITE.''\\/plugins\\/cck_storage_location'';\\r\\nif ( count( $options ) ) {\\r\\n  foreach ( $options as $o ) {\\r\\n    if ( $o->value == ''<OPTGROUP>'' || $o->value == ''<\\/OPTGROUP>'' ) {\\r\\n      continue;\\r\\n    }\\r\\n    $pp = array( ''custom'' );\\r\\n    if ( is_file( $base.''\\/''.$o->value.''\\/''.$o->value.''.php'' ) ) {\\r\\n      require_once $base.''\\/''.$o->value.''\\/''.$o->value.''.php'';\\r\\n      $pp = JCck::callFunc( ''plgCCK_Storage_Location''.$o->value,''getStaticProperties'',$pp );\\r\\n      $v  = $pp[''custom''];\\r\\n    } else {\\r\\n      $v  = '''';\\r\\n    }\\r\\n    $o->$attr = ''data-custom=\\"''.$v.''\\"'';\\r\\n  }\\r\\n}\\r\\n\\r\\n$attr = ''class=\\"inputbox select\\" size=\\"1\\" ''.$field->attributes;\\r\\n$attr = array( ''id''=>$id,\\r\\n               ''list.attr''=>$attr,\\r\\n               ''list.select''=>$value,\\r\\n               ''list.translate''=>FALSE,\\r\\n               ''option.attr''=>''data-cck'',\\r\\n               ''option.key''=>''value'',\\r\\n               ''option.text''=>''text''\\r\\n        );\\r\\n$form = JHtml::_( ''select.genericlist'', $options, $name, $attr );","preparestore":""}' WHERE `id` = 66;
UPDATE `#__cck_core_fields` SET `options` = 'Hide=-1||Show=optgroup||Filename Title=0||Icon=1||Image=2||Thumb1=3||Thumb2=4||Thumb3=5||Thumb4=6||Thumb5=7||Thumb6=8||Thumb7=9||Thumb8=10||Thumb9=11||Thumb10=12' WHERE `id` = 113;
UPDATE `#__cck_core_fields` SET `options` = 'No Process=0||Resized=optgroup||Crop=crop||Shrink=shrink||Stretch=stretch||Resized Dynamic=optgroup||Max Fit=maxfit||Shrink=shrink_dynamic||Stretch=stretch_dynamic', `css` = 'max-width-190' WHERE `id` = 117;
UPDATE `#__cck_core_fields` SET `options` = 'Resized=optgroup||Crop=crop||Shrink=shrink||Stretch=stretch||Resized Dynamic=optgroup||Max Fit=maxfit||Shrink=shrink_dynamic||Stretch=stretch_dynamic', `css` = 'max-width-190' WHERE `id` = 120;
UPDATE `#__cck_core_fields` SET `defaultvalue` = 'category zebra table' WHERE `id` = 235;
UPDATE `#__cck_core_fields` SET `label` = 'Smart Search', `options` = 'Smart Search Indexing=optgroup||Content=content||Intro=intro' WHERE `id` = 257;
UPDATE `#__cck_core_fields` SET `options2` = '{"preparecontent":"","prepareform":"$options = array();\\r\\nif ( trim( $field->selectlabel ) ) {\\r\\n  $options = array( JHtml::_( ''select.option'',  '''', ''- ''.$field->selectlabel.'' -'' ),\\r\\n                    JHtml::_( ''select.option'', ''none'', JText::_( ''COM_CCK_NONE'' ) ) );\\r\\n} else {\\r\\n  $value = ( $value ) ? $value : ''joomla_article'';\\r\\n  $options = array( JHtml::_( ''select.option'', ''none'', JText::_( ''COM_CCK_NONE'' ) ) );\\r\\n}\\r\\n$class = $field->css ? '' ''.$field->css : '''';\\r\\n$options = array_merge( $options, Helper_Admin::getPluginOptions( ''storage_location'', ''cck_'', false, false, true ) );\\r\\n$form = JHtml::_( ''select.genericlist'', $options, $name, ''class=\\"inputbox select''.$class.''\\" size=\\"1\\" ''.$field->attributes, ''value'', ''text'', $value, $id );","preparestore":""}' WHERE `id` = 275;

UPDATE `#__cck_core_fields` SET `bool8` = 1 WHERE `type` IN ("checkbox","radio","search_ordering","select_simple","select_multiple","select_dynamic") AND `id` != 289;
