
ALTER TABLE `#__cck_core_searchs` ADD `location` VARCHAR( 50 ) NOT NULL AFTER `options`;

INSERT IGNORE INTO `#__cck_core_fields` (`id`, `title`, `name`, `folder`, `type`, `description`, `published`, `label`, `selectlabel`, `display`, `required`, `validation`, `defaultvalue`, `options`, `options2`, `minlength`, `maxlength`, `size`, `cols`, `rows`, `ordering`, `sorting`, `divider`, `bool`, `location`, `extended`, `style`, `script`, `bool2`, `bool3`, `bool4`, `bool5`, `bool6`, `bool7`, `bool8`, `css`, `attributes`, `storage`, `storage_location`, `storage_table`, `storage_field`, `storage_field2`, `storage_params`, `storages`, `checked_out`, `checked_out_time`) VALUES
(284, 'Core Location2', 'core_location2', 3, 'select_simple', '', 0, 'List Location', ' ', 3, '', '', '', 'Both=||Location=optgroup||Administrator=admin||Site=site', '{"options":[]}', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'location', '', '', '', 0, '0000-00-00 00:00:00'),
(285, 'Core Filter Go', 'core_filter_go', 3, 'button_submit', '', 0, 'Go', ' ', 3, '', '', '', '', '{"icon":"checkmark","alt_link_text":"","alt_link":"","alt_link_options":""}', 0, 255, 32, 0, 0, 0, 0, '', 1, '', '', '', '', 0, 1, 0, 0, 3, 1, 0, 'tip hasTooltip', 'onclick="this.form.submit();"', 'none', '', '', 'core_filter_go', '', '', '', 0, '0000-00-00 00:00:00'),
(286, 'Core Filter Search', 'core_filter_search', 3, 'button_submit', '', 0, 'Search', ' ', 3, '', '', '', '', '{"icon":"search","alt_link_text":"","alt_link":"","alt_link_options":""}', 0, 255, 32, 0, 0, 0, 0, '', 1, '', '', '', '', 0, 1, 0, 0, 3, 0, 0, 'tip hasTooltip', 'onclick="this.form.submit();"', 'none', '', '', 'core_filter_search', '', '', '', 0, '0000-00-00 00:00:00'),
(287, 'Core Filter Clear', 'core_filter_clear', 3, 'button_submit', '', 0, 'Clear', ' ', 3, '', '', '', '', '{"icon":"remove","alt_link_text":"","alt_link":"","alt_link_options":""}', 0, 255, 32, 0, 0, 0, 0, '', 1, '', '', '', '', 0, 1, 0, 0, 3, 0, 0, 'tip hasTooltip', 'onclick="this.form.submit();"', 'none', '', '', 'core_filter_clear', '', '', '', 0, '0000-00-00 00:00:00'),
(288, 'Core Filter Input', 'core_filter_input', 3, 'text', '', 0, 'Search', ' ', 3, '', '', '', '', '', 0, 255, 20, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'filter_search', '', '', '', 0, '0000-00-00 00:00:00'),
(289, 'Core Icons', 'core_icons', 3, 'select_simple', '', 0, 'Icon', 'Select', 3, '', '', '', 'address||arrow-down||arrow-down-2||arrow-down-3||arrow-first||arrow-last||arrow-left||arrow-left-2||arrow-left-3||arrow-right||arrow-right-2||arrow-right-3||arrow-up||arrow-up-2||arrow-up-3||bars||basket||bookmark||box-add||box-remove||briefcase||broadcast||brush||calendar||calendar-2||camera||camera-2||cancel||cart||chart||checkbox||checkbox-partial||checkbox-unchecked||checkmark||clock||cog||cogs||color-palette||comments||comments-2||compass||contract||contract-2||copy||cube||delete||dashboard||database||download||drawer||drawer-2||equalizer||expand||expand-2||eye||feed||file||file-add||file-remove||filter||first||flag||flag-2||folder-close||folder-open||grid-view||grid-view-2||health||help||home||key||lamp||last||lightning||list-view||location||lock||loop||mail||mail-2||menu||menu-2||minus||minus-2||mobile||move||music||next||out||out-2||pencil||pencil-2||picture||pictures||pie||pin||play||play-2||plus||plus-2||power-cord||previous||print||puzzle||quote||quote-2||refresh||remove||screen||search||share||shuffle||star||star-2||star-empty||support||tablet||thumbs-down||thumbs-up||tools||trash||undo||upload||user||users||vcard||wand||warning||wrench||zoom-in||zoom-out', '{"options":[]}', 0, 255, 32, 0, 0, 0, 0, '', 0, '', '', '', '', 0, 0, 0, 0, 0, 0, 0, '', '', 'dev', '', '', 'json[options2][icon]', '', '', '', 0, '0000-00-00 00:00:00');

UPDATE `#__cck_core_fields` SET `options2` = '{"preparecontent":"","prepareform":"if ( $value == ''0'' ) {\\r\\n $c0 = ''checked=\\"checked\\"''; $c1 = ''''; $class = ''unpublish icon-unpublish'';\\r\\n} else {\\r\\n $c0 = ''''; $c1 = ''checked=\\"checked\\"''; $class = ''publish icon-publish'';\\r\\n}\\r\\n$form = ''<div>''\\r\\n      . ''<input type=\\"radio\\" id=\\"state0\\" name=\\"''.$name.''\\" value=\\"0\\" ''.$c0\\r\\n      . '' style=\\"display:none;\\" \\/>''\\r\\n      . ''<input type=\\"radio\\" id=\\"state1\\" name=\\"''.$name.''\\" value=\\"1\\" ''.$c1\\r\\n      . '' style=\\"display:none;\\" \\/>''\\r\\n      . ''<a href=\\"javascript: void(0);\\" id=\\"state\\" class=\\"jgrid\\">''\\r\\n      . ''<span class=\\"state ''.$class.''\\">''\\r\\n      . ''<\\/span>''\\r\\n      . ''<\\/a>''\\r\\n      . ''<\\/div>'';","preparestore":""}', `script` = '$("#state").click(function(){\r\n $("#state input").removeAttr("checked");\r\n if ( $("#state0").prop("checked") == true ) {\r\n  $("#state span").removeClass("unpublish icon-unpublish").addClass("publish icon-publish");\r\n  $("#state1").attr("checked", "checked");\r\n } else {\r\n  $("#state span").removeClass("publish icon-publish").addClass("unpublish icon-unpublish");\r\n  $("#state0").attr("checked", "checked");\r\n }\r\n});' WHERE `id` = 43;
UPDATE `#__cck_core_fields` SET `options2` = '{"preparecontent":"","prepareform":"$options = Helper_Admin::getLocationOptions();\\r\\n$class = $field->css ? '' ''.$field->css : '''';\\r\\n$form = JHtml::_( ''select.genericlist'', $options, $name, ''class=\\"inputbox select''.$class.''\\" size=\\"1\\" ''.$field->attributes, ''value'', ''text'', $value, $id );","preparestore":""}', `css` = 'hidden-phone' WHERE `id` = 46;

UPDATE `#__cck_core_fields` SET `bool4` = 2 WHERE `type` = "select_dynamic" AND `bool4` = 1 AND `bool5` = 0;
UPDATE `#__cck_core_fields` SET `bool5` = 0 WHERE `type` = "select_dynamic" AND `bool4` = 1 AND `bool5` = 1;