
UPDATE `#__cck_core_fields` SET `options` = 'Joomla=optgroup||Prepend Segment=10||Use Native=0||SEBLOD=optgroup||SEF Mode Alias=23||SEF Mode Id=22||SEF Mode Id Alias=2||SEBLOD Advanced=optgroup||SEF Mode Author Alias=53||SEF Mode Author Id=52||SEF Mode Author Id Alias=5||SEF Mode Parent Alias=43||SEF Mode Parent Id=42||SEF Mode Parent Id Alias=4||SEF Mode Parents Alias=83||SEF Mode Parents Id=82||SEF Mode Parents Id Alias=8||SEF Mode Type Alias=33||SEF Mode Type Id=32||SEF Mode Type Id Alias=3||SEBLOD Deprecated=optgroup||SEF Mode Alias Safe=24||Optimized=1' WHERE `id` = 177;

UPDATE `#__cck_core_fields` SET `options2` = '{"query":"","table":"#__cck_core_types","name":"title","where":"parent = \\"\\" AND storage_location != \\"none\\" AND published != -44","value":"name","orderby":"title","orderby_direction":"ASC","limit":"","language_detection":"joomla","language_codes":"EN,GB,US,FR","language_default":"EN","attr1":"","attr2":"","attr3":"","attr4":"","attr5":"","attr6":""}' WHERE `id` = 531;

UPDATE `#__cck_core_fields` SET `script` = '$("fieldset#layer").on("click", "label", function() {\r\n $("#layer label").removeClass(\'selected\'); $(this).addClass(\'selected\');\r\n var current = $("#"+$(this).attr(\'for\'));\r\n if (current.prop("checked") != true) {\r\n  $("#layer input").prop("checked", false); current.prop("checked", true);\r\n  $(".layers").slideUp();  $("#layer_"+current.val()).slideDown();\r\n }\r\n});' WHERE `id` = 57;

UPDATE `#__cck_core_fields` SET `script` = '$("#title").on("change", function() {\r\n  if ( !$("#name").val() ) {\r\n    JCck.Dev.transliterateName();\r\n  }\r\n}); if( !$("#title").val() ) { $("#title").focus(); }' WHERE `id` = 27;
UPDATE `#__cck_core_fields` SET `script` = '$("#title").on("change", function() {\r\n  if ( !$("#name").val() ) {\r\n    JCck.DevHelper.transliterateName();\r\n  }\r\n}); if( !$("#title").val() ) { $("#title").focus(); }' WHERE `id` = 38;
UPDATE `#__cck_core_fields` SET `script` = '$("#title").on("change", function() {\r\n  if ( !$("#name").val() ) {\r\n    JCck.DevHelper.transliterateName();\r\n  }\r\n}); if( !$("#title").val() ) { $("#title").focus(); }' WHERE `id` = 39;

UPDATE `#__cck_core_fields` SET `options2` = '{"preparecontent":"","prepareform":"$form = JCckDev::getForm( \'core_conditional_trigger_type\', \'\', $config, array() )\\r\\n      .\\tJCckDev::getForm( \'core_conditional_trigger_value\', \'\', $config,\\r\\n        array( \'css\'=>\'trigger-type\' ) )\\r\\n      . \'&nbsp;<span class=\\"fill trigger-value\\" name=\\"\'.$field->location.\'\\">&laquo;<\\/span>\';\\r\\n$js = \'\\r\\n$(\\".trigger-value\\").on(\\"click\\", function() {\\r\\nvar url = \\"index.php?option=com_cck&task=box.add&tmpl=component&file=administrator\\/components\\/com_cck\\/views\\/field\\/tmpl\\/selection.php&title=conditional&name=\'.$field->extended.\'&type=\'.$field->location.\'\\";\\r\\n$.fn.colorbox({href:url, iframe:true, innerWidth:300, innerHeight:200, scrolling:false, overlayClose:false, fixed:true, onLoad: function(){ $(\\"#cboxClose\\").remove();}}); });\';\\r\\n$field->script = $js;","preparestore":""}' WHERE `id` = 457;

UPDATE `#__cck_core_fields` SET `options2` = '{"preparecontent":"","prepareform":"$class = \'icon-lock \';\\r\\n$value = $field->defaultvalue;\\r\\nif ( $value == \'0\' ) {\\r\\n $c0 = \'checked=\\"checked\\"\'; $c1 = \'\'; $class .= \'unlinked\';\\r\\n} else {\\r\\n $c0 = \'\'; $c1 = \'checked=\\"checked\\"\'; $class .= \'linked\';\\r\\n}\\r\\n$desc = JText::_( \'COM_CCK_STORAGE_DESC_SHORT\' );\\r\\n$form = \'<input type=\\"radio\\" id=\\"\'.$name.\'0\\" name=\\"\'.$name.\'\\" value=\\"0\\" \'.$c0\\r\\n      . \' style=\\"display:none;\\" \\/>\'\\r\\n      . \'<input type=\\"radio\\" id=\\"\'.$name.\'1\\" name=\\"\'.$name.\'\\" value=\\"1\\" \'.$c1\\r\\n      . \' style=\\"display:none;\\" \\/>\'\\r\\n      . \'<a href=\\"javascript: void(0);\\" id=\\"\'.$name.\'\\" class=\\"switch hasTooltip\\" title=\\"\'\\r\\n      . $desc.\'\\">\'\\r\\n      . \'<span class=\\"\'.$name.\' \'.$class.\'\\">\'\\r\\n      . \'<\\/span>\'\\r\\n      . \'<\\/a>\';","preparestore":""}' WHERE `id` = 106;
