
CREATE TABLE IF NOT EXISTS `#__cck_more_countries` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name_en` varchar(255) NOT NULL,
  `name_fr` varchar(255) NOT NULL,
  `code2` varchar(5) NOT NULL,
  `code3` varchar(5) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=247 ;


-- --------------------------------------------------------


INSERT IGNORE INTO `#__cck_more_countries` (`id`, `name_en`, `name_fr`, `code2`, `code3`) VALUES
(1, 'Afghanistan', 'Afghanistan', 'AF', 'AFG'),
(2, 'Aland Islands', 'Åland, îles', 'AX', 'ALA'),
(3, 'Albania', 'Albanie', 'AL', 'ALB'),
(4, 'Algeria', 'Algérie', 'DZ', 'DZA'),
(5, 'American Samoa', 'Samoa américaines', 'AS', 'ASM'),
(6, 'Andorra', 'Andorre', 'AD', 'AND'),
(7, 'Angola', 'Angola', 'AO', 'AGO'),
(8, 'Anguilla', 'Anguilla', 'AI', 'AIA'),
(9, 'Antarctica', 'Antarctique', 'AQ', 'ATA'),
(10, 'Antigua and Barbuda', 'Antigua-et-barbuda', 'AG', 'ATG'),
(11, 'Argentina', 'Argentine', 'AR', 'ARG'),
(12, 'Armenia', 'Arménie', 'AM', 'ARM'),
(13, 'Aruba', 'Aruba', 'AW', 'ABW'),
(14, 'Australia', 'Australie', 'AU', 'AUS'),
(15, 'Austria', 'Autriche', 'AT', 'AUT'),
(16, 'Azerbaijan', 'Azerbaïdjan', 'AZ', 'AZE'),
(17, 'Bahamas', 'Bahamas', 'BS', 'BHS'),
(18, 'Bahrain', 'Bahreïn', 'BH', 'BHR'),
(19, 'Bangladesh', 'Bangladesh', 'BD', 'BGD'),
(20, 'Barbados', 'Barbade', 'BB', 'BRB'),
(21, 'Belarus', 'Bélarus', 'BY', 'BLR'),
(22, 'Belgium', 'Belgique', 'BE', 'BEL'),
(23, 'Belize', 'Belize', 'BZ', 'BLZ'),
(24, 'Benin', 'Bénin', 'BJ', 'BEN'),
(25, 'Bermuda', 'Bermudes', 'BM', 'BMU'),
(26, 'Bhutan', 'Bhoutan', 'BT', 'BTN'),
(27, 'Bolivia, Plurinational State of', 'Bolivie, l''état plurinational de', 'BO', 'BOL'),
(28, 'Bosnia and Herzegovina', 'Bosnie-herzégovine', 'BA', 'BIH'),
(29, 'Botswana', 'Botswana', 'BW', 'BWA'),
(30, 'Bouvet Island', 'Bouvet, île', 'BV', 'BVT'),
(31, 'Brazil', 'Brésil', 'BR', 'BRA'),
(32, 'British Indian Ocean Territory', 'Océan indien, territoire britannique de l''', 'IO', 'IOT'),
(33, 'Brunei Darussalam', 'Brunéi darussalam', 'BN', 'BRN'),
(34, 'Bulgaria', 'Bulgarie', 'BG', 'BGR'),
(35, 'Burkina Faso', 'Burkina faso', 'BF', 'BFA'),
(36, 'Burundi', 'Burundi', 'BI', 'BDI'),
(37, 'Cambodia', 'Cambodge', 'KH', 'KHM'),
(38, 'Cameroon', 'Cameroun', 'CM', 'CMR'),
(39, 'Canada', 'Canada', 'CA', 'CAN'),
(40, 'Cape Verde', 'Cap-vert', 'CV', 'CPV'),
(41, 'Cayman Islands', 'Caïmanes, îles', 'KY', 'CYM'),
(42, 'Central African Republic', 'Centrafricaine, république', 'CF', 'CAF'),
(43, 'Chad', 'Tchad', 'TD', 'TCD'),
(44, 'Chile', 'Chili', 'CL', 'CHL'),
(45, 'China', 'Chine', 'CN', 'CHN'),
(46, 'Christmas Island', 'Christmas, île', 'CX', 'CXR'),
(47, 'Cocos (Keeling) Islands', 'Cocos (keeling), îles', 'CC', 'CCK'),
(48, 'Colombia', 'Colombie', 'CO', 'COL'),
(49, 'Comoros', 'Comores', 'KM', 'COM'),
(50, 'Congo', 'Congo', 'CG', 'COG'),
(51, 'Congo, the Democratic Republic of the', 'Congo, la république démocratique du', 'CD', 'COD'),
(52, 'Cook Islands', 'Cook, îles', 'CK', 'COK'),
(53, 'Costa Rica', 'Costa rica', 'CR', 'CRI'),
(54, 'Cote d''Ivoire', 'Côte d''ivoire', 'CI', 'CIV'),
(55, 'Croatia', 'Croatie', 'HR', 'HRV'),
(56, 'Cuba', 'Cuba', 'CU', 'CUB'),
(57, 'Cyprus', 'Chypre', 'CY', 'CYP'),
(58, 'Czech Republic', 'Tchèque, république', 'CZ', 'CZE'),
(59, 'Denmark', 'Danemark', 'DK', 'DNK'),
(60, 'Djibouti', 'Djibouti', 'DJ', 'DJI'),
(61, 'Dominica', 'Dominique', 'DM', 'DMA'),
(62, 'Dominican Republic', 'Dominicaine, république', 'DO', 'DOM'),
(63, 'Ecuador', 'Équateur', 'EC', 'ECU'),
(64, 'Egypt', 'Égypte', 'EG', 'EGY'),
(65, 'El Salvador', 'El salvador', 'SV', 'SLV'),
(66, 'Equatorial Guinea', 'Guinée équatoriale', 'GQ', 'GNQ'),
(67, 'Eritrea', 'Érythrée', 'ER', 'ERI'),
(68, 'Estonia', 'Estonie', 'EE', 'EST'),
(69, 'Ethiopia', 'Éthiopie', 'ET', 'ETH'),
(70, 'Falkland Islands (Malvinas)', 'Falkland, îles (malvinas)', 'FK', 'FLK'),
(71, 'Faroe Islands', 'Féroé, îles', 'FO', 'FRO'),
(72, 'Fiji', 'Fidji', 'FJ', 'FJI'),
(73, 'Finland', 'Finlande', 'FI', 'FIN'),
(74, 'France', 'France', 'FR', 'FRA'),
(75, 'French Guiana', 'Guyane française', 'GF', 'GUF'),
(76, 'French Polynesia', 'Polynésie française', 'PF', 'PYF'),
(77, 'French Southern Territories', 'Terres australes françaises', 'TF', 'ATF'),
(78, 'Gabon', 'Gabon', 'GA', 'GAB'),
(79, 'Gambia', 'Gambie', 'GM', 'GMB'),
(80, 'Georgia', 'Géorgie', 'GE', 'GEO'),
(81, 'Germany', 'Allemagne', 'DE', 'DEU'),
(82, 'Ghana', 'Ghana', 'GH', 'GHA'),
(83, 'Gibraltar', 'Gibraltar', 'GI', 'GIB'),
(84, 'Greece', 'Grèce', 'GR', 'GRC'),
(85, 'Greenland', 'Groenland', 'GL', 'GRL'),
(86, 'Grenada', 'Grenade', 'GD', 'GRD'),
(87, 'Guadeloupe', 'Guadeloupe', 'GP', 'GLP'),
(88, 'Guam', 'Guam', 'GU', 'GUM'),
(89, 'Guatemala', 'Guatemala', 'GT', 'GTM'),
(90, 'Guernsey', 'Guernesey', 'GG', 'GGY'),
(91, 'Guinea', 'Guinée', 'GN', 'GIN'),
(92, 'Guinea-Bissau', 'Guinée-bissau', 'GW', 'GNB'),
(93, 'Guyana', 'Guyana', 'GY', 'GUY'),
(94, 'Haiti', 'Haïti', 'HT', 'HTI'),
(95, 'Heard Island and McDonald Islands', 'Heard, île et mcdonald, îles', 'HM', 'HMD'),
(96, 'Holy See (Vatican City State)', 'Saint-siège (état de la cité du vatican)', 'VA', 'VAT'),
(97, 'Honduras', 'Honduras', 'HN', 'HND'),
(98, 'Hong Kong', 'Hong-kong', 'HK', 'HKG'),
(99, 'Hungary', 'Hongrie', 'HU', 'HUN'),
(100, 'Iceland', 'Islande', 'IS', 'ISL'),
(101, 'India', 'Inde', 'IN', 'IND'),
(102, 'Indonesia', 'Indonésie', 'ID', 'IDN'),
(103, 'Iran, Islamic Republic of', 'Iran, république islamique d''', 'IR', 'IRN'),
(104, 'Iraq', 'Iraq', 'IQ', 'IRQ'),
(105, 'Ireland', 'Irlande', 'IE', 'IRL'),
(106, 'Isle of Man', 'Île de man', 'IM', 'IMN'),
(107, 'Israel', 'Israël', 'IL', 'ISR'),
(108, 'Italy', 'Italie', 'IT', 'ITA'),
(109, 'Jamaica', 'Jamaïque', 'JM', 'JAM'),
(110, 'Japan', 'Japon', 'JP', 'JPN'),
(111, 'Jersey', 'Jersey', 'JE', 'JEY'),
(112, 'Jordan', 'Jordanie', 'JO', 'JOR'),
(113, 'Kazakhstan', 'Kazakhstan', 'KZ', 'KAZ'),
(114, 'Kenya', 'Kenya', 'KE', 'KEN'),
(115, 'Kiribati', 'Kiribati', 'KI', 'KIR'),
(116, 'Korea, Democratic People''s Republic of', 'Corée, république populaire démocratique de', 'KP', 'PRK'),
(117, 'South Korea', 'Corée du Sud', 'KR', 'KOR'),
(118, 'Kuwait', 'Koweït', 'KW', 'KWT'),
(119, 'Kyrgyzstan', 'Kirghizistan', 'KG', 'KGZ'),
(120, 'Lao People''s Democratic Republic', 'Lao, république démocratique populaire', 'LA', 'LAO'),
(121, 'Latvia', 'Lettonie', 'LV', 'LVA'),
(122, 'Lebanon', 'Liban', 'LB', 'LBN'),
(123, 'Lesotho', 'Lesotho', 'LS', 'LSO'),
(124, 'Liberia', 'Libéria', 'LR', 'LBR'),
(125, 'Libyan Arab Jamahiriya', 'Libyenne, jamahiriya arabe', 'LY', 'LBY'),
(126, 'Liechtenstein', 'Liechtenstein', 'LI', 'LIE'),
(127, 'Lithuania', 'Lituanie', 'LT', 'LTU'),
(128, 'Luxembourg', 'Luxembourg', 'LU', 'LUX'),
(129, 'Macao', 'Macao', 'MO', 'MAC'),
(130, 'Macedonia, the former Yugoslav Republic of', 'Macédoine, l''ex-république yougoslave de', 'MK', 'MKD'),
(131, 'Madagascar', 'Madagascar', 'MG', 'MDG'),
(132, 'Malawi', 'Malawi', 'MW', 'MWI'),
(133, 'Malaysia', 'Malaisie', 'MY', 'MYS'),
(134, 'Maldives', 'Maldives', 'MV', 'MDV'),
(135, 'Mali', 'Mali', 'ML', 'MLI'),
(136, 'Malta', 'Malte', 'MT', 'MLT'),
(137, 'Marshall Islands', 'Marshall, îles', 'MH', 'MHL'),
(138, 'Martinique', 'Martinique', 'MQ', 'MTQ'),
(139, 'Mauritania', 'Mauritanie', 'MR', 'MRT'),
(140, 'Mauritius', 'Maurice', 'MU', 'MUS'),
(141, 'Mayotte', 'Mayotte', 'YT', 'MYT'),
(142, 'Mexico', 'Mexique', 'MX', 'MEX'),
(143, 'Micronesia, Federated States of', 'Micronésie, états fédérés de', 'FM', 'FSM'),
(144, 'Moldova, Republic of', 'Moldova, république de', 'MD', 'MDA'),
(145, 'Monaco', 'Monaco', 'MC', 'MCO'),
(146, 'Mongolia', 'Mongolie', 'MN', 'MNG'),
(147, 'Montenegro', 'Monténégro', 'ME', 'MNE'),
(148, 'Montserrat', 'Montserrat', 'MS', 'MSR'),
(149, 'Morocco', 'Maroc', 'MA', 'MAR'),
(150, 'Mozambique', 'Mozambique', 'MZ', 'MOZ'),
(151, 'Myanmar', 'Myanmar', 'MM', 'MMR'),
(152, 'Namibia', 'Namibie', 'NA', 'NAM'),
(153, 'Nauru', 'Nauru', 'NR', 'NRU'),
(154, 'Nepal', 'Népal', 'NP', 'NPL'),
(155, 'Netherlands', 'Pays-bas', 'NL', 'NLD'),
(156, 'Netherlands Antilles', 'Antilles néerlandaises', 'AN', 'ANT'),
(157, 'New Caledonia', 'Nouvelle-calédonie', 'NC', 'NCL'),
(158, 'New Zealand', 'Nouvelle-zélande', 'NZ', 'NZL'),
(159, 'Nicaragua', 'Nicaragua', 'NI', 'NIC'),
(160, 'Niger', 'Niger', 'NE', 'NER'),
(161, 'Nigeria', 'Nigéria', 'NG', 'NGA'),
(162, 'Niue', 'Niué', 'NU', 'NIU'),
(163, 'Norfolk Island', 'Norfolk, île', 'NF', 'NFK'),
(164, 'Northern Mariana Islands', 'Mariannes du nord, îles', 'MP', 'MNP'),
(165, 'Norway', 'Norvège', 'NO', 'NOR'),
(166, 'Oman', 'Oman', 'OM', 'OMN'),
(167, 'Pakistan', 'Pakistan', 'PK', 'PAK'),
(168, 'Palau', 'Palaos', 'PW', 'PLW'),
(169, 'Palestinian Territory, Occupied', 'Palestinien occupé, territoire', 'PS', 'PSE'),
(170, 'Panama', 'Panama', 'PA', 'PAN'),
(171, 'Papua New Guinea', 'Papouasie-nouvelle-guinée', 'PG', 'PNG'),
(172, 'Paraguay', 'Paraguay', 'PY', 'PRY'),
(173, 'Peru', 'Pérou', 'PE', 'PER'),
(174, 'Philippines', 'Philippines', 'PH', 'PHL'),
(175, 'Pitcairn', 'Pitcairn', 'PN', 'PCN'),
(176, 'Poland', 'Pologne', 'PL', 'POL'),
(177, 'Portugal', 'Portugal', 'PT', 'PRT'),
(178, 'Puerto Rico', 'Porto rico', 'PR', 'PRI'),
(179, 'Qatar', 'Qatar', 'QA', 'QAT'),
(180, 'Reunion', 'Réunion', 'RE', 'REU'),
(181, 'Romania', 'Roumanie', 'RO', 'ROU'),
(182, 'Russian Federation', 'Russie, fédération de', 'RU', 'RUS'),
(183, 'Rwanda', 'Rwanda', 'RW', 'RWA'),
(184, 'Saint Barthelemy', 'Saint-barthélemy', 'BL', 'BLM'),
(185, 'Saint Helena', 'Sainte-hélène, ascension et tristan da cunha', 'SH', 'SHN'),
(186, 'Saint Kitts and Nevis', 'Saint-kitts-et-nevis', 'KN', 'KNA'),
(187, 'Saint Lucia', 'Sainte-lucie', 'LC', 'LCA'),
(188, 'Saint Martin (French part)', 'Saint-martin', 'MF', 'MAF'),
(189, 'Saint Pierre and Miquelon', 'Saint-pierre-et-miquelon', 'PM', 'SPM'),
(190, 'Saint Vincent and the Grenadines', 'Saint-vincent-et-les grenadines', 'VC', 'VCT'),
(191, 'Samoa', 'Samoa', 'WS', 'WSM'),
(192, 'San Marino', 'Saint-marin', 'SM', 'SMR'),
(193, 'Sao Tome and Principe', 'Sao tomé-et-principe', 'ST', 'STP'),
(194, 'Saudi Arabia', 'Arabie saoudite', 'SA', 'SAU'),
(195, 'Senegal', 'Sénégal', 'SN', 'SEN'),
(196, 'Serbia', 'Serbie', 'RS', 'SRB'),
(197, 'Seychelles', 'Seychelles', 'SC', 'SYC'),
(198, 'Sierra Leone', 'Sierra leone', 'SL', 'SLE'),
(199, 'Singapore', 'Singapour', 'SG', 'SGP'),
(200, 'Slovakia', 'Slovaquie', 'SK', 'SVK'),
(201, 'Slovenia', 'Slovénie', 'SI', 'SVN'),
(202, 'Solomon Islands', 'Salomon, îles', 'SB', 'SLB'),
(203, 'Somalia', 'Somalie', 'SO', 'SOM'),
(204, 'South Africa', 'Afrique du sud', 'ZA', 'ZAF'),
(205, 'South Georgia and South Sandwich Islands', 'Géorgie du sud et les îles sandwich du sud', 'GS', 'SGS'),
(206, 'Spain', 'Espagne', 'ES', 'ESP'),
(207, 'Sri Lanka', 'Sri lanka', 'LK', 'LKA'),
(208, 'Sudan', 'Soudan', 'SD', 'SDN'),
(209, 'Suriname', 'Suriname', 'SR', 'SUR'),
(210, 'Svalbard and Jan Mayen', 'Svalbard et île jan mayen', 'SJ', 'SJM'),
(211, 'Swaziland', 'Swaziland', 'SZ', 'SWZ'),
(212, 'Sweden', 'Suède', 'SE', 'SWE'),
(213, 'Switzerland', 'Suisse', 'CH', 'CHE'),
(214, 'Syrian Arab Republic', 'Syrienne, république arabe', 'SY', 'SYR'),
(215, 'Taiwan, Province of China', 'Taïwan, province de chine', 'TW', 'TWN'),
(216, 'Tajikistan', 'Tadjikistan', 'TJ', 'TJK'),
(217, 'Tanzania, United Republic of', 'Tanzanie, république-unie de', 'TZ', 'TZA'),
(218, 'Thailand', 'Thaïlande', 'TH', 'THA'),
(219, 'Timor-Leste', 'Timor-leste', 'TL', 'TLS'),
(220, 'Togo', 'Togo', 'TG', 'TGO'),
(221, 'Tokelau', 'Tokelau', 'TK', 'TKL'),
(222, 'Tonga', 'Tonga', 'TO', 'TON'),
(223, 'Trinidad and Tobago', 'Trinité-et-tobago', 'TT', 'TTO'),
(224, 'Tunisia', 'Tunisie', 'TN', 'TUN'),
(225, 'Turkey', 'Turquie', 'TR', 'TUR'),
(226, 'Turkmenistan', 'Turkménistan', 'TM', 'TKM'),
(227, 'Turks and Caicos Islands', 'Turks et caïques, îles', 'TC', 'TCA'),
(228, 'Tuvalu', 'Tuvalu', 'TV', 'TUV'),
(229, 'Uganda', 'Ouganda', 'UG', 'UGA'),
(230, 'Ukraine', 'Ukraine', 'UA', 'UKR'),
(231, 'United Arab Emirates', 'Émirats arabes unis', 'AE', 'ARE'),
(232, 'United Kingdom', 'Royaume-uni', 'GB', 'GBR'),
(233, 'United States', 'États-unis', 'US', 'USA'),
(234, 'United States Minor Outlying Islands', 'Îles mineures éloignées des états-unis', 'UM', 'UMI'),
(235, 'Uruguay', 'Uruguay', 'UY', 'URY'),
(236, 'Uzbekistan', 'Ouzbékistan', 'UZ', 'UZB'),
(237, 'Vanuatu', 'Vanuatu', 'VU', 'VUT'),
(238, 'Venezuela, Bolivarian Republic of', 'Venezuela, république bolivarienne du', 'VE', 'VEN'),
(239, 'Viet Nam', 'Viet nam', 'VN', 'VNM'),
(240, 'Virgin Islands, British', 'Îles vierges britanniques', 'VG', 'VGB'),
(241, 'Virgin Islands, U.S.', 'Îles vierges des états-unis', 'VI', 'VIR'),
(242, 'Wallis and Futuna', 'Wallis et futuna', 'WF', 'WLF'),
(243, 'Western Sahara', 'Sahara occidental', 'EH', 'ESH'),
(244, 'Yemen', 'Yémen', 'YE', 'YEM'),
(245, 'Zambia', 'Zambie', 'ZM', 'ZMB'),
(246, 'Zimbabwe', 'Zimbabwe', 'ZW', 'ZWE');