
CREATE TABLE IF NOT EXISTS `#__cck_more_countries` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name_en` varchar(255) NOT NULL,
  `name_fr` varchar(255) NOT NULL,
  `name_de` varchar(255) NOT NULL,
  `code2` varchar(5) NOT NULL,
  `code3` varchar(5) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=247 ;


-- --------------------------------------------------------


INSERT IGNORE INTO `#__cck_more_countries` (`id`, `name_en`, `name_fr`, `name_de`, `code2`, `code3`) VALUES
(1, 'Afghanistan', 'Afghanistan', 'Afghanistan', 'AF', 'AFG'),
(2, 'Aland Islands', 'Åland, îles', 'Åland', 'AX', 'ALA'),
(3, 'Albania', 'Albanie', 'Albanien', 'AL', 'ALB'),
(4, 'Algeria', 'Algérie', 'Algerien', 'DZ', 'DZA'),
(5, 'American Samoa', 'Samoa américaines', 'Amerikanisch Samoa', 'AS', 'ASM'),
(6, 'Andorra', 'Andorre', 'Andorra', 'AD', 'AND'),
(7, 'Angola', 'Angola', 'Angola', 'AO', 'AGO'),
(8, 'Anguilla', 'Anguilla', 'Anguilla', 'AI', 'AIA'),
(9, 'Antarctica', 'Antarctique', 'Antarktis', 'AQ', 'ATA'),
(10, 'Antigua and Barbuda', 'Antigua-et-barbuda', 'Antigua und Barbuda', 'AG', 'ATG'),
(11, 'Argentina', 'Argentine', 'Argentinien', 'AR', 'ARG'),
(12, 'Armenia', 'Arménie', 'Armenien', 'AM', 'ARM'),
(13, 'Aruba', 'Aruba', 'Aruba', 'AW', 'ABW'),
(14, 'Australia', 'Australie', 'Australien', 'AU', 'AUS'),
(15, 'Austria', 'Autriche', 'Österreich', 'AT', 'AUT'),
(16, 'Azerbaijan', 'Azerbaïdjan', 'Aserbaidschan', 'AZ', 'AZE'),
(17, 'Bahamas', 'Bahamas', 'Bahamas', 'BS', 'BHS'),
(18, 'Bahrain', 'Bahreïn', 'Bahrain', 'BH', 'BHR'),
(19, 'Bangladesh', 'Bangladesh', 'Bangladesch', 'BD', 'BGD'),
(20, 'Barbados', 'Barbade', 'Barbados', 'BB', 'BRB'),
(21, 'Belarus', 'Bélarus', 'Weißrussland', 'BY', 'BLR'),
(22, 'Belgium', 'Belgique', 'Belgien', 'BE', 'BEL'),
(23, 'Belize', 'Belize', 'Belize', 'BZ', 'BLZ'),
(24, 'Benin', 'Bénin', 'Benin', 'BJ', 'BEN'),
(25, 'Bermuda', 'Bermudes', 'Bermuda', 'BM', 'BMU'),
(26, 'Bhutan', 'Bhoutan', 'Bhutan', 'BT', 'BTN'),
(27, 'Bolivia, Plurinational State of', 'Bolivie, l''état plurinational de', 'Bolivien', 'BO', 'BOL'),
(28, 'Bosnia and Herzegovina', 'Bosnie-herzégovine', 'Bosnien und Herzegowina', 'BA', 'BIH'),
(29, 'Botswana', 'Botswana', 'Botsuana', 'BW', 'BWA'),
(30, 'Bouvet Island', 'Bouvet, île', 'Bouvetinsel', 'BV', 'BVT'),
(31, 'Brazil', 'Brésil', 'Brasilien', 'BR', 'BRA'),
(32, 'British Indian Ocean Territory', 'Océan indien, territoire britannique de l''', 'Britische Territorien im Indischen Ozean', 'IO', 'IOT'),
(33, 'Brunei Darussalam', 'Brunéi darussalam', 'Brunei Darussalam', 'BN', 'BRN'),
(34, 'Bulgaria', 'Bulgarie', 'Bulgarien', 'BG', 'BGR'),
(35, 'Burkina Faso', 'Burkina faso', 'Burkina Faso', 'BF', 'BFA'),
(36, 'Burundi', 'Burundi', 'Burundi', 'BI', 'BDI'),
(37, 'Cambodia', 'Cambodge', 'Kambodscha', 'KH', 'KHM'),
(38, 'Cameroon', 'Cameroun', 'Kamerun', 'CM', 'CMR'),
(39, 'Canada', 'Canada', 'Kanada', 'CA', 'CAN'),
(40, 'Cape Verde', 'Cap-vert', 'Kap Verde', 'CV', 'CPV'),
(41, 'Cayman Islands', 'Caïmanes, îles', 'Kaimaninseln', 'KY', 'CYM'),
(42, 'Central African Republic', 'Centrafricaine, république', 'Zentralafrikanische Republik', 'CF', 'CAF'),
(43, 'Chad', 'Tchad', 'Tschad', 'TD', 'TCD'),
(44, 'Chile', 'Chili', 'Chile', 'CL', 'CHL'),
(45, 'China', 'Chine', 'China', 'CN', 'CHN'),
(46, 'Christmas Island', 'Christmas, île', 'Weihnachtsinsel', 'CX', 'CXR'),
(47, 'Cocos (Keeling) Islands', 'Cocos (keeling), îles', 'Kokosinseln', 'CC', 'CCK'),
(48, 'Colombia', 'Colombie', 'Kolumbien', 'CO', 'COL'),
(49, 'Comoros', 'Comores', 'Komoren', 'KM', 'COM'),
(50, 'Congo', 'Congo', 'Kongo', 'CG', 'COG'),
(51, 'Congo, the Democratic Republic of the', 'Congo, la république démocratique du', 'Kongo, Dem. Rep.', 'CD', 'COD'),
(52, 'Cook Islands', 'Cook, îles', 'Cookinseln', 'CK', 'COK'),
(53, 'Costa Rica', 'Costa rica', 'Costa Rica', 'CR', 'CRI'),
(54, 'Cote d''Ivoire', 'Côte d''ivoire', 'Elfenbeinküste', 'CI', 'CIV'),
(55, 'Croatia', 'Croatie', 'Kroatien', 'HR', 'HRV'),
(56, 'Cuba', 'Cuba', 'Kuba', 'CU', 'CUB'),
(57, 'Cyprus', 'Chypre', 'Zypern', 'CY', 'CYP'),
(58, 'Czech Republic', 'Tchèque, république', 'Tschechische Republik', 'CZ', 'CZE'),
(59, 'Denmark', 'Danemark', 'Dänemark', 'DK', 'DNK'),
(60, 'Djibouti', 'Djibouti', 'Republik Dschibuti', 'DJ', 'DJI'),
(61, 'Dominica', 'Dominique', 'Dominica', 'DM', 'DMA'),
(62, 'Dominican Republic', 'Dominicaine, république', 'Dominikanische Republik', 'DO', 'DOM'),
(63, 'Ecuador', 'Équateur', 'Ecuador', 'EC', 'ECU'),
(64, 'Egypt', 'Égypte', 'Ägypten', 'EG', 'EGY'),
(65, 'El Salvador', 'El salvador', 'El Salvador', 'SV', 'SLV'),
(66, 'Equatorial Guinea', 'Guinée équatoriale', 'Äquatorialguinea', 'GQ', 'GNQ'),
(67, 'Eritrea', 'Érythrée', 'Eritrea', 'ER', 'ERI'),
(68, 'Estonia', 'Estonie', 'Estland', 'EE', 'EST'),
(69, 'Ethiopia', 'Éthiopie', 'Äthiopien', 'ET', 'ETH'),
(70, 'Falkland Islands (Malvinas)', 'Falkland, îles (malvinas)', 'Falklandinseln', 'FK', 'FLK'),
(71, 'Faroe Islands', 'Féroé, îles', 'Färöer', 'FO', 'FRO'),
(72, 'Fiji', 'Fidji', 'Fidschi', 'FJ', 'FJI'),
(73, 'Finland', 'Finlande', 'Finnland', 'FI', 'FIN'),
(74, 'France', 'France', 'Frankreich', 'FR', 'FRA'),
(75, 'French Guiana', 'Guyane française', 'Französisch-Guayana', 'GF', 'GUF'),
(76, 'French Polynesia', 'Polynésie française', 'Französisch-Polynesien', 'PF', 'PYF'),
(77, 'French Southern Territories', 'Terres australes françaises', 'Französische Südgebiete', 'TF', 'ATF'),
(78, 'Gabon', 'Gabon', 'Gabun', 'GA', 'GAB'),
(79, 'Gambia', 'Gambie', 'Gambia', 'GM', 'GMB'),
(80, 'Georgia', 'Géorgie', 'Georgien', 'GE', 'GEO'),
(81, 'Germany', 'Allemagne', 'Deutschland', 'DE', 'DEU'),
(82, 'Ghana', 'Ghana', 'Ghana', 'GH', 'GHA'),
(83, 'Gibraltar', 'Gibraltar', 'Gibraltar', 'GI', 'GIB'),
(84, 'Greece', 'Grèce', 'Griechenland', 'GR', 'GRC'),
(85, 'Greenland', 'Groenland', 'Grönland', 'GL', 'GRL'),
(86, 'Grenada', 'Grenade', 'Grenada', 'GD', 'GRD'),
(87, 'Guadeloupe', 'Guadeloupe', 'Guadeloupe', 'GP', 'GLP'),
(88, 'Guam', 'Guam', 'Guam', 'GU', 'GUM'),
(89, 'Guatemala', 'Guatemala', 'Guatemala', 'GT', 'GTM'),
(90, 'Guernsey', 'Guernesey', 'Guernsey', 'GG', 'GGY'),
(91, 'Guinea', 'Guinée', 'Guinea', 'GN', 'GIN'),
(92, 'Guinea-Bissau', 'Guinée-bissau', 'Guinea-Bissau', 'GW', 'GNB'),
(93, 'Guyana', 'Guyana', 'Guyana', 'GY', 'GUY'),
(94, 'Haiti', 'Haïti', 'Haiti', 'HT', 'HTI'),
(95, 'Heard Island and McDonald Islands', 'Heard, île et mcdonald, îles', 'Heard Insel und McDonald Inseln', 'HM', 'HMD'),
(96, 'Holy See (Vatican City State)', 'Saint-siège (état de la cité du vatican)', 'Vatikanstadt', 'VA', 'VAT'),
(97, 'Honduras', 'Honduras', 'Honduras', 'HN', 'HND'),
(98, 'Hong Kong', 'Hong-kong', 'Hong Kong', 'HK', 'HKG'),
(99, 'Hungary', 'Hongrie', 'Ungarn', 'HU', 'HUN'),
(100, 'Iceland', 'Islande', 'Island', 'IS', 'ISL'),
(101, 'India', 'Inde', 'Indien', 'IN', 'IND'),
(102, 'Indonesia', 'Indonésie', 'Indonesien', 'ID', 'IDN'),
(103, 'Iran, Islamic Republic of', 'Iran, république islamique d''', 'Iran, Islam. Rep.', 'IR', 'IRN'),
(104, 'Iraq', 'Iraq', 'Irak', 'IQ', 'IRQ'),
(105, 'Ireland', 'Irlande', 'Irland', 'IE', 'IRL'),
(106, 'Isle of Man', 'Île de man', 'Isle of Man', 'IM', 'IMN'),
(107, 'Israel', 'Israël', 'Israel', 'IL', 'ISR'),
(108, 'Italy', 'Italie', 'Italien', 'IT', 'ITA'),
(109, 'Jamaica', 'Jamaïque', 'Jamaika', 'JM', 'JAM'),
(110, 'Japan', 'Japon', 'Japan', 'JP', 'JPN'),
(111, 'Jersey', 'Jersey', 'Jersey', 'JE', 'JEY'),
(112, 'Jordan', 'Jordanie', 'Jordanien', 'JO', 'JOR'),
(113, 'Kazakhstan', 'Kazakhstan', 'Kasachstan', 'KZ', 'KAZ'),
(114, 'Kenya', 'Kenya', 'Kenia', 'KE', 'KEN'),
(115, 'Kiribati', 'Kiribati', 'Kiribati', 'KI', 'KIR'),
(116, 'Korea, Democratic People''s Republic of', 'Corée, république populaire démocratique de', 'Korea, Dem. Volksrep.', 'KP', 'PRK'),
(117, 'South Korea', 'Corée du Sud', 'Korea, Rep.', 'KR', 'KOR'),
(118, 'Kuwait', 'Koweït', 'Kuwait', 'KW', 'KWT'),
(119, 'Kyrgyzstan', 'Kirghizistan', 'Kirgisistan', 'KG', 'KGZ'),
(120, 'Lao People''s Democratic Republic', 'Lao, république démocratique populaire', 'Laos, Dem. Volksrep.', 'LA', 'LAO'),
(121, 'Latvia', 'Lettonie', 'Lettland', 'LV', 'LVA'),
(122, 'Lebanon', 'Liban', 'Libanon', 'LB', 'LBN'),
(123, 'Lesotho', 'Lesotho', 'Lesotho', 'LS', 'LSO'),
(124, 'Liberia', 'Libéria', 'Liberia', 'LR', 'LBR'),
(125, 'Libyan Arab Jamahiriya', 'Libyenne, jamahiriya arabe', 'Libysch-Arabische Dschamahirija', 'LY', 'LBY'),
(126, 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'LI', 'LIE'),
(127, 'Lithuania', 'Lituanie', 'Litauen', 'LT', 'LTU'),
(128, 'Luxembourg', 'Luxembourg', 'Luxemburg', 'LU', 'LUX'),
(129, 'Macao', 'Macao', 'Macao', 'MO', 'MAC'),
(130, 'Macedonia, the former Yugoslav Republic of', 'Macédoine, l''ex-république yougoslave de', 'Mazedonien, ehemalige jugoslawische Republik ', 'MK', 'MKD'),
(131, 'Madagascar', 'Madagascar', 'Madagaskar', 'MG', 'MDG'),
(132, 'Malawi', 'Malawi', 'Malawi', 'MW', 'MWI'),
(133, 'Malaysia', 'Malaisie', 'Malaysia', 'MY', 'MYS'),
(134, 'Maldives', 'Maldives', 'Malediven', 'MV', 'MDV'),
(135, 'Mali', 'Mali', 'Mali', 'ML', 'MLI'),
(136, 'Malta', 'Malte', 'Malta', 'MT', 'MLT'),
(137, 'Marshall Islands', 'Marshall, îles', 'Marshallinseln', 'MH', 'MHL'),
(138, 'Martinique', 'Martinique', 'Martinique', 'MQ', 'MTQ'),
(139, 'Mauritania', 'Mauritanie', 'Mauretanien', 'MR', 'MRT'),
(140, 'Mauritius', 'Maurice', 'Mauritius', 'MU', 'MUS'),
(141, 'Mayotte', 'Mayotte', 'Mayotte', 'YT', 'MYT'),
(142, 'Mexico', 'Mexique', 'Mexiko', 'MX', 'MEX'),
(143, 'Micronesia, Federated States of', 'Micronésie, états fédérés de', 'Mikronesien, Föderierte Staaten von', 'FM', 'FSM'),
(144, 'Moldova, Republic of', 'Moldova, république de', 'Moldau, Rep.', 'MD', 'MDA'),
(145, 'Monaco', 'Monaco', 'Monaco', 'MC', 'MCO'),
(146, 'Mongolia', 'Mongolie', 'Mongolei', 'MN', 'MNG'),
(147, 'Montenegro', 'Monténégro', 'Montenegro', 'ME', 'MNE'),
(148, 'Montserrat', 'Montserrat', 'Montserrat', 'MS', 'MSR'),
(149, 'Morocco', 'Maroc', 'Marokko', 'MA', 'MAR'),
(150, 'Mozambique', 'Mozambique', 'Mosambik', 'MZ', 'MOZ'),
(151, 'Myanmar', 'Myanmar', 'Myanmar', 'MM', 'MMR'),
(152, 'Namibia', 'Namibie', 'Namibia', 'NA', 'NAM'),
(153, 'Nauru', 'Nauru', 'Nauru', 'NR', 'NRU'),
(154, 'Nepal', 'Népal', 'Nepal', 'NP', 'NPL'),
(155, 'Netherlands', 'Pays-bas', 'Niederlande', 'NL', 'NLD'),
(156, 'Netherlands Antilles', 'Antilles néerlandaises', 'Niederländische Antillen', 'AN', 'ANT'),
(157, 'New Caledonia', 'Nouvelle-calédonie', 'Neukaledonien', 'NC', 'NCL'),
(158, 'New Zealand', 'Nouvelle-zélande', 'Neuseeland', 'NZ', 'NZL'),
(159, 'Nicaragua', 'Nicaragua', 'Nicaragua', 'NI', 'NIC'),
(160, 'Niger', 'Niger', 'Niger', 'NE', 'NER'),
(161, 'Nigeria', 'Nigéria', 'Nigeria', 'NG', 'NGA'),
(162, 'Niue', 'Niué', 'Niue', 'NU', 'NIU'),
(163, 'Norfolk Island', 'Norfolk, île', 'Norfolk Insel', 'NF', 'NFK'),
(164, 'Northern Mariana Islands', 'Mariannes du nord, îles', 'Nördliche Marianen', 'MP', 'MNP'),
(165, 'Norway', 'Norvège', 'Norwegen', 'NO', 'NOR'),
(166, 'Oman', 'Oman', 'Oman', 'OM', 'OMN'),
(167, 'Pakistan', 'Pakistan', 'Pakistan', 'PK', 'PAK'),
(168, 'Palau', 'Palaos', 'Palau', 'PW', 'PLW'),
(169, 'Palestinian Territory, Occupied', 'Palestinien occupé, territoire', 'Palästinensische Autonomiegebiete', 'PS', 'PSE'),
(170, 'Panama', 'Panama', 'Panama', 'PA', 'PAN'),
(171, 'Papua New Guinea', 'Papouasie-nouvelle-guinée', 'Papua-Neuguinea', 'PG', 'PNG'),
(172, 'Paraguay', 'Paraguay', 'Paraguay', 'PY', 'PRY'),
(173, 'Peru', 'Pérou', 'Peru', 'PE', 'PER'),
(174, 'Philippines', 'Philippines', 'Philippinen', 'PH', 'PHL'),
(175, 'Pitcairn', 'Pitcairn', 'Pitcairn', 'PN', 'PCN'),
(176, 'Poland', 'Pologne', 'Polen', 'PL', 'POL'),
(177, 'Portugal', 'Portugal', 'Portugal', 'PT', 'PRT'),
(178, 'Puerto Rico', 'Porto rico', 'Puerto Rico', 'PR', 'PRI'),
(179, 'Qatar', 'Qatar', 'Katar', 'QA', 'QAT'),
(180, 'Reunion', 'Réunion', 'Réunion', 'RE', 'REU'),
(181, 'Romania', 'Roumanie', 'Rum', 'RO', 'ROU'),
(182, 'Russian Federation', 'Russie, fédération de', 'Russland', 'RU', 'RUS'),
(183, 'Rwanda', 'Rwanda', 'Ruanda', 'RW', 'RWA'),
(184, 'Saint Barthelemy', 'Saint-barthélemy', 'St. Barth', 'BL', 'BLM'),
(185, 'Saint Helena', 'Sainte-hélène, ascension et tristan da cunha', 'Saint Helena', 'SH', 'SHN'),
(186, 'Saint Kitts and Nevis', 'Saint-kitts-et-nevis', 'St. Kitts und Nevis', 'KN', 'KNA'),
(187, 'Saint Lucia', 'Sainte-lucie', 'St. Lucia', 'LC', 'LCA'),
(188, 'Saint Martin (French part)', 'Saint-martin', 'St. Martin', 'MF', 'MAF'),
(189, 'Saint Pierre and Miquelon', 'Saint-pierre-et-miquelon', 'Saint Pierre und Miquelon', 'PM', 'SPM'),
(190, 'Saint Vincent and the Grenadines', 'Saint-vincent-et-les grenadines', 'St. Vincent und die Grenadinen', 'VC', 'VCT'),
(191, 'Samoa', 'Samoa', 'Samoa', 'WS', 'WSM'),
(192, 'San Marino', 'Saint-marin', 'San Marino', 'SM', 'SMR'),
(193, 'Sao Tome and Principe', 'Sao tomé-et-principe', 'São Tomé und Príncipe', 'ST', 'STP'),
(194, 'Saudi Arabia', 'Arabie saoudite', 'Saudi-Arabien', 'SA', 'SAU'),
(195, 'Senegal', 'Sénégal', 'Senegal', 'SN', 'SEN'),
(196, 'Serbia', 'Serbie', 'Serbien', 'RS', 'SRB'),
(197, 'Seychelles', 'Seychelles', 'Seychellen', 'SC', 'SYC'),
(198, 'Sierra Leone', 'Sierra leone', 'Sierra Leone', 'SL', 'SLE'),
(199, 'Singapore', 'Singapour', 'Singapur', 'SG', 'SGP'),
(200, 'Slovakia', 'Slovaquie', 'Slowakei', 'SK', 'SVK'),
(201, 'Slovenia', 'Slovénie', 'Slowenien', 'SI', 'SVN'),
(202, 'Solomon Islands', 'Salomon, îles', 'Salomonen', 'SB', 'SLB'),
(203, 'Somalia', 'Somalie', 'Somalia', 'SO', 'SOM'),
(204, 'South Africa', 'Afrique du sud', 'Südafrika', 'ZA', 'ZAF'),
(205, 'South Georgia and South Sandwich Islands', 'Géorgie du sud et les îles sandwich du sud', 'Südgeorgien und die Südlichen Sandwichinseln', 'GS', 'SGS'),
(206, 'Spain', 'Espagne', 'Spanien', 'ES', 'ESP'),
(207, 'Sri Lanka', 'Sri lanka', 'Sri Lanka', 'LK', 'LKA'),
(208, 'Sudan', 'Soudan', 'Sudan', 'SD', 'SDN'),
(209, 'Suriname', 'Suriname', 'Suriname', 'SR', 'SUR'),
(210, 'Svalbard and Jan Mayen', 'Svalbard et île jan mayen', 'Svalbard und Jan Mayen', 'SJ', 'SJM'),
(211, 'Swaziland', 'Swaziland', 'Swasiland', 'SZ', 'SWZ'),
(212, 'Sweden', 'Suède', 'Schweden', 'SE', 'SWE'),
(213, 'Switzerland', 'Suisse', 'Schweiz', 'CH', 'CHE'),
(214, 'Syrian Arab Republic', 'Syrienne, république arabe', 'Syrien, Arab. Rep.', 'SY', 'SYR'),
(215, 'Taiwan, Province of China', 'Taïwan, province de chine', 'Taiwan', 'TW', 'TWN'),
(216, 'Tajikistan', 'Tadjikistan', 'Tadschikistan', 'TJ', 'TJK'),
(217, 'Tanzania, United Republic of', 'Tanzanie, république-unie de', 'Tansania, Vereinigte Rep.', 'TZ', 'TZA'),
(218, 'Thailand', 'Thaïlande', 'Thailand', 'TH', 'THA'),
(219, 'Timor-Leste', 'Timor-leste', 'Timor-Leste', 'TL', 'TLS'),
(220, 'Togo', 'Togo', 'Togo', 'TG', 'TGO'),
(221, 'Tokelau', 'Tokelau', 'Tokelau', 'TK', 'TKL'),
(222, 'Tonga', 'Tonga', 'Tonga', 'TO', 'TON'),
(223, 'Trinidad and Tobago', 'Trinité-et-tobago', 'Trinidad und Tobago', 'TT', 'TTO'),
(224, 'Tunisia', 'Tunisie', 'Tunesien', 'TN', 'TUN'),
(225, 'Turkey', 'Turquie', 'Türkei', 'TR', 'TUR'),
(226, 'Turkmenistan', 'Turkménistan', 'Turkmenistan', 'TM', 'TKM'),
(227, 'Turks and Caicos Islands', 'Turks et caïques, îles', 'Turks- und Caicosinseln', 'TC', 'TCA'),
(228, 'Tuvalu', 'Tuvalu', 'Tuvalu', 'TV', 'TUV'),
(229, 'Uganda', 'Ouganda', 'Uganda', 'UG', 'UGA'),
(230, 'Ukraine', 'Ukraine', 'Ukraine', 'UA', 'UKR'),
(231, 'United Arab Emirates', 'Émirats arabes unis', 'Vereinigte Arabische Emirate', 'AE', 'ARE'),
(232, 'United Kingdom', 'Royaume-uni', 'Vereinigtes Königreich', 'GB', 'GBR'),
(233, 'United States', 'États-unis', 'Vereinigte Staaten von Amerika', 'US', 'USA'),
(234, 'United States Minor Outlying Islands', 'Îles mineures éloignées des états-unis', 'United States Minor Outlying Islands', 'UM', 'UMI'),
(235, 'Uruguay', 'Uruguay', 'Uruguay', 'UY', 'URY'),
(236, 'Uzbekistan', 'Ouzbékistan', 'Usbekistan', 'UZ', 'UZB'),
(237, 'Vanuatu', 'Vanuatu', 'Vanuatu', 'VU', 'VUT'),
(238, 'Venezuela, Bolivarian Republic of', 'Venezuela, république bolivarienne du', 'Venezuela', 'VE', 'VEN'),
(239, 'Viet Nam', 'Viet nam', 'Vietnam', 'VN', 'VNM'),
(240, 'Virgin Islands, British', 'Îles vierges britanniques', 'Britische Jungferninseln', 'VG', 'VGB'),
(241, 'Virgin Islands, U.S.', 'Îles vierges des états-unis', 'Amerikanische Jungferninseln', 'VI', 'VIR'),
(242, 'Wallis and Futuna', 'Wallis et futuna', 'Wallis und Futuna', 'WF', 'WLF'),
(243, 'Western Sahara', 'Sahara occidental', 'Westsahara', 'EH', 'ESH'),
(244, 'Yemen', 'Yémen', 'Jemen', 'YE', 'YEM'),
(245, 'Zambia', 'Zambie', 'Sambia', 'ZM', 'ZMB'),
(246, 'Zimbabwe', 'Zimbabwe', 'Simbabwe', 'ZW', 'ZWE');
